(function(){var aa="_imgFileNameError",ba="_imgUrlTextError",ca="about:invalid#zClosurez",da="allHolder",ea="aria-expanded",fa="bgresponse",ha="chooseWidget",ia="commentBodyField",e="complete",ja="displayModeLayout",ka="displayModeNone",h="div",la="encodedSelectedId",m="function",ma="goog-zippy-collapsed",oa="goog-zippy-expanded",pa="hidden",qa="identity-type-",ra="identityHolder",sa="identityMenu",ta="input",ua="keypress",va="layout-widget-description",wa="layout-widget-title",xa="main-status-holder",ya="nameUrlIdentityHolder",
n="none",za="number",p="object",Aa="postCommentSubmit",Ba="ready",Ca="rotate(-45deg)",Da="sectionWidth",Ea="select-multiple",Fa="showPreview",Ga="status-message",Ha="status-message-inner",r="string",Ia="subscribeButtonHolder",Ja="success",Ka="true",t,La=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},Ma=Ma||{},u=this||self,v=function(a,b,c){a=a.split(".");c=c||u;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=
a.shift());)a.length||void 0===b?c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}:c[d]=b},Na=/^[\w+/_-]+[=]{0,2}$/,Oa=null,Pa=function(){},Qa=function(a){a.uc=void 0;a.ng=function(){return a.uc?a.uc:a.uc=new a}},Ra=function(a){var b=typeof a;if(b==p)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return p;if("[object Array]"==c||typeof a.length==za&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&
!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return m}else return"null";else if(b==m&&"undefined"==typeof a.call)return p;return b},w=function(a){return"array"==Ra(a)},Sa=function(a){var b=Ra(a);return"array"==b||b==p&&typeof a.length==za},Ta=function(a){return Ra(a)==m},Ua=function(a){var b=typeof a;return b==p&&null!=a||b==m},Va="closure_uid_"+(1E9*Math.random()>>>
0),Wa=0,Xa=function(a,b,c){return a.call.apply(a.bind,arguments)},Ya=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var f=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(f,d);return a.apply(b,f)}}return function(){return a.apply(b,arguments)}},x=function(a,b,c){x=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?Xa:Ya;return x.apply(null,arguments)},Za=Date.now||function(){return+new Date},
y=function(a,b){function c(){}c.prototype=b.prototype;a.l=b.prototype;a.prototype=new c;a.prototype.constructor=a};var $a=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,$a);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};y($a,Error);$a.prototype.name="CustomError";var ab;var bb=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,f=0;f<d;f++)c+=a[f]+(f<b.length?b[f]:"%s");$a.call(this,c+a[d])};y(bb,$a);bb.prototype.name="AssertionError";var cb=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(typeof a===r)return typeof b!==r||1!=b.length?-1:a.indexOf(b,c);for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},eb=Array.prototype.lastIndexOf?function(a,b,c){return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(typeof a===r)return typeof b!==r||1!=b.length?
-1:a.lastIndexOf(b,c);for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1},fb=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=typeof a===r?a.split(""):a,g=0;g<d;g++)g in f&&b.call(c,f[g],g,a)},gb=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=[],g=0,k=typeof a===r?a.split(""):a,l=0;l<d;l++)if(l in k){var q=k[l];b.call(c,q,l,a)&&(f[g++]=q)}return f},hb=Array.prototype.map?
function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=Array(d),g=typeof a===r?a.split(""):a,k=0;k<d;k++)k in g&&(f[k]=b.call(c,g[k],k,a));return f},ib=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,f=typeof a===r?a.split(""):a,g=0;g<d;g++)if(g in f&&b.call(c,f[g],g,a))return!0;return!1},jb=function(a,b,c){a:{for(var d=a.length,f=typeof a===r?a.split(""):a,g=0;g<d;g++)if(g in f&&b.call(c,f[g],g,
a)){b=g;break a}b=-1}return 0>b?null:typeof a===r?a.charAt(b):a[b]},z=function(a,b){return 0<=cb(a,b)},kb=function(a){if(!w(a))for(var b=a.length-1;0<=b;b--)delete a[b];a.length=0},lb=function(a,b){b=cb(a,b);var c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c},mb=function(a){return Array.prototype.concat.apply([],arguments)},nb=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},ob=function(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,
b):Array.prototype.slice.call(a,b,c)};var pb=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},qb=/&/g,rb=/</g,sb=/>/g,tb=/"/g,ub=/'/g,vb=/\x00/g,wb=/[\x00&<>"']/,A=function(a,b){return-1!=a.indexOf(b)},xb=function(a,b){return a<b?-1:a>b?1:0};var B;a:{var yb=u.navigator;if(yb){var Ab=yb.userAgent;if(Ab){B=Ab;break a}}B=""};var Bb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},Cb=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},Db=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b},Eb=function(a,b){for(var c in a)if(a[c]==b)return!0;return!1},Fb=function(a){for(var b in a)return!1;return!0},Gb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Hb=function(a,b){for(var c,d,f=1;f<arguments.length;f++){d=arguments[f];for(c in d)a[c]=d[c];for(var g=
0;g<Gb.length;g++)c=Gb[g],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}},Ib=function(a){var b=arguments.length;if(1==b&&w(arguments[0]))return Ib.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c};var Jb=function(a){return a};var Mb=function(a,b){this.Te=a===Kb&&b||"";this.zf=Lb};Mb.prototype.Y=!0;Mb.prototype.T=function(){return this.Te};var Lb={},Kb={};var Nb=function(){this.ve=""};Nb.prototype.Y=!0;Nb.prototype.T=function(){return this.ve.toString()};Nb.prototype.G=function(a){this.ve=a;return this};(new Nb).G("");var Qb=function(a,b){this.xe=a===Ob&&b||"";this.Kf=Pb};Qb.prototype.Y=!0;Qb.prototype.T=function(){return this.xe.toString()};var Pb={},Ob={};var C=function(a,b){this.we=a===Rb&&b||"";this.yf=Sb};C.prototype.Y=!0;C.prototype.T=function(){return this.we.toString()};var Tb=function(a){if(a instanceof C&&a.constructor===C&&a.yf===Sb)return a.we;Ra(a);return"type_error:SafeUrl"},Ub=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,Vb=function(a){if(a instanceof C)return a;a=typeof a==p&&a.Y?a.T():String(a);Ub.test(a)||(a=ca);return new C(Rb,a)},Sb={},Rb={};var D=function(){this.Kc="";this.xf=Wb};D.prototype.Y=!0;var Wb={};D.prototype.T=function(){return this.Kc};D.prototype.G=function(a){this.Kc=a;return this};
var Xb=(new D).G(""),dc=function(a){if(a instanceof C)return'url("'+Tb(a).replace(/</g,"%3c").replace(/[\\"]/g,"\\$&")+'")';if(a instanceof Mb)a=a instanceof Mb&&a.constructor===Mb&&a.zf===Lb?a.Te:"type_error:Const";else{a=String(a);var b=a.replace(Yb,"$1").replace(Yb,"$1").replace(Zb,"url");if($b.test(b)){if(b=!ac.test(a)){for(var c=b=!0,d=0;d<a.length;d++){var f=a.charAt(d);"'"==f&&c?b=!b:'"'==f&&b&&(c=!c)}b=b&&c&&bc(a)}a=b?cc(a):"zClosurez"}else a="zClosurez"}if(/[{;}]/.test(a))throw new bb("Value does not allow [{;}], got: %s.",
[a]);return a},bc=function(a){for(var b=!0,c=/^[-_a-zA-Z0-9]$/,d=0;d<a.length;d++){var f=a.charAt(d);if("]"==f){if(b)return!1;b=!0}else if("["==f){if(!b)return!1;b=!1}else if(!b&&!c.test(f))return!1}return b},$b=/^[-,."'%_!# a-zA-Z0-9\[\]]+$/,Zb=/\b(url\([ \t\n]*)('[ -&(-\[\]-~]*'|"[ !#-\[\]-~]*"|[!#-&*-\[\]-~]*)([ \t\n]*\))/g,Yb=/\b(calc|cubic-bezier|fit-content|hsl|hsla|matrix|minmax|repeat|rgb|rgba|(rotate|scale|translate)(X|Y|Z|3d)?)\([-+*/0-9a-z.%\[\], ]+\)/g,ac=/\/\*/,cc=function(a){return a.replace(Zb,
function(b,c,d,f){var g="";d=d.replace(/^(['"])(.*)\1$/,function(k,l,q){g=l;return q});b=Vb(d).T();return c+g+b+g+f})};var fc=function(){this.Jc="";this.wf=ec};fc.prototype.Y=!0;
var ec={},gc=function(a,b){if(A(a,"<"))throw Error("Selector does not allow '<', got: "+a);var c=a.replace(/('|")((?!\1)[^\r\n\f\\]|\\[\s\S])*\1/g,"");if(!/^[-_a-zA-Z0-9#.:* ,>+~[\]()=^$|]+$/.test(c))throw Error("Selector allows only [-_a-zA-Z0-9#.:* ,>+~[\\]()=^$|] and strings, got: "+a);a:{for(var d={"(":")","[":"]"},f=[],g=0;g<c.length;g++){var k=c[g];if(d[k])f.push(d[k]);else if(Eb(d,k)&&f.pop()!=k){c=!1;break a}}c=0==f.length}if(!c)throw Error("() and [] in selector must be balanced, got: "+a);
if(!(b instanceof D)){c="";for(var l in b){if(!/^[-_a-zA-Z0-9]+$/.test(l))throw Error("Name allows only [-_a-zA-Z0-9], got: "+l);d=b[l];null!=d&&(d=w(d)?hb(d,dc).join(" "):dc(d),c+=l+":"+d+";")}b=c?(new D).G(c):Xb}b instanceof D&&b.constructor===D&&b.xf===Wb?l=b.Kc:(Ra(b),l="type_error:SafeStyle");a=a+"{"+l.replace(/</g,"\\3C ")+"}";return(new fc).G(a)},ic=function(a){var b="",c=function(d){w(d)?fb(d,c):b+=hc(d)};fb(arguments,c);return(new fc).G(b)};fc.prototype.T=function(){return this.Jc};
var hc=function(a){if(a instanceof fc&&a.constructor===fc&&a.wf===ec)return a.Jc;Ra(a);return"type_error:SafeStyleSheet"};fc.prototype.G=function(a){this.Jc=a;return this};(new fc).G("");var jc=function(){this.ue=""};jc.prototype.Y=!0;jc.prototype.T=function(){return this.ue.toString()};jc.prototype.G=function(a){this.ue=a;return this};(new jc).G("<!DOCTYPE html>",0);(new jc).G("",0);(new jc).G("<br>",0);var kc=function(a){return a.replace(/(\r\n|\r|\n)+/g," ")},lc=function(a){return a.replace(/\xa0|[ \t]+/g," ")},mc=function(a,b){b?a=a.replace(qb,"&amp;").replace(rb,"&lt;").replace(sb,"&gt;").replace(tb,"&quot;").replace(ub,"&#39;").replace(vb,"&#0;"):wb.test(a)&&(-1!=a.indexOf("&")&&(a=a.replace(qb,"&amp;")),-1!=a.indexOf("<")&&(a=a.replace(rb,"&lt;")),-1!=a.indexOf(">")&&(a=a.replace(sb,"&gt;")),-1!=a.indexOf('"')&&(a=a.replace(tb,"&quot;")),-1!=a.indexOf("'")&&(a=a.replace(ub,"&#39;")),-1!=a.indexOf("\x00")&&
(a=a.replace(vb,"&#0;")));return a};var nc=function(a){nc[" "](a);return a};nc[" "]=Pa;var oc=function(a,b,c,d){d=d?d(b):b;return Object.prototype.hasOwnProperty.call(a,d)?a[d]:a[d]=c(b)};var pc=A(B,"Opera"),F=A(B,"Trident")||A(B,"MSIE"),qc=A(B,"Edge"),G=A(B,"Gecko")&&!(A(B.toLowerCase(),"webkit")&&!A(B,"Edge"))&&!(A(B,"Trident")||A(B,"MSIE"))&&!A(B,"Edge"),H=A(B.toLowerCase(),"webkit")&&!A(B,"Edge"),rc=A(B,"Macintosh"),sc=function(){var a=u.document;return a?a.documentMode:void 0},tc;
a:{var uc="",vc=function(){var a=B;if(G)return/rv:([^\);]+)(\)|;)/.exec(a);if(qc)return/Edge\/([\d\.]+)/.exec(a);if(F)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(H)return/WebKit\/(\S+)/.exec(a);if(pc)return/(?:Version)[ \/]?(\S+)/.exec(a)}();vc&&(uc=vc?vc[1]:"");if(F){var wc=sc();if(null!=wc&&wc>parseFloat(uc)){tc=String(wc);break a}}tc=uc}
var xc=tc,yc={},zc=function(a){return oc(yc,a,function(){for(var b=0,c=pb(String(xc)).split("."),d=pb(String(a)).split("."),f=Math.max(c.length,d.length),g=0;0==b&&g<f;g++){var k=c[g]||"",l=d[g]||"";do{k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];l=/(\d*)(\D*)(.*)/.exec(l)||["","","",""];if(0==k[0].length&&0==l[0].length)break;b=xb(0==k[1].length?0:parseInt(k[1],10),0==l[1].length?0:parseInt(l[1],10))||xb(0==k[2].length,0==l[2].length)||xb(k[2],l[2]);k=k[3];l=l[3]}while(0==b)}return 0<=b})},Ac;
Ac=u.document&&F?sc():void 0;var Bc=!F||9<=Number(Ac);var Cc=function(a,b){this.width=a;this.height=b};Cc.prototype.clone=function(){return new Cc(this.width,this.height)};Cc.prototype.Uf=function(){return this.width*this.height};Cc.prototype.isEmpty=function(){return!this.Uf()};Cc.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var Ec=function(a){return a?new Dc(9==a.nodeType?a:a.ownerDocument||a.document):ab||(ab=new Dc)},K=function(a){return typeof a===r?document.getElementById(a):a},Gc=function(a,b){Bb(b,function(c,d){c&&typeof c==p&&c.Y&&(c=c.T());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:Fc.hasOwnProperty(d)?a.setAttribute(Fc[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})},Fc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",
frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},Ic=function(a,b,c){return Hc(document,arguments)},Hc=function(a,b){var c=String(b[0]),d=b[1];if(!Bc&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',mc(d.name),'"');if(d.type){c.push(' type="',mc(d.type),'"');var f={};Hb(f,d);delete f.type;d=f}c.push(">");c=c.join("")}c=Jc(a,c);d&&(typeof d===r?c.className=d:w(d)?c.className=
d.join(" "):Gc(c,d));2<b.length&&Kc(a,c,b,2);return c},Kc=function(a,b,c,d){function f(k){k&&b.appendChild(typeof k===r?a.createTextNode(k):k)}for(;d<c.length;d++){var g=c[d];!Sa(g)||Ua(g)&&0<g.nodeType?f(g):fb(Lc(g)?nb(g):g,f)}},Jc=function(a,b){b=String(b);"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)},Mc=function(a){for(var b;b=a.firstChild;)a.removeChild(b)},Lc=function(a){if(a&&typeof a.length==za){if(Ua(a))return typeof a.item==m||typeof a.item==r;if(Ta(a))return typeof a.item==
m}return!1},Dc=function(a){this.ma=a||u.document||document};t=Dc.prototype;t.Na=function(a){return typeof a===r?this.ma.getElementById(a):a};t.getElementsByTagName=function(a,b){return(b||this.ma).getElementsByTagName(String(a))};
t.Hd=function(a,b,c){c=c||this.ma;a=a&&"*"!=a?String(a).toUpperCase():"";if(c.querySelectorAll&&c.querySelector&&(a||b))b=c.querySelectorAll(a+(b?"."+b:""));else if(b&&c.getElementsByClassName)if(c=c.getElementsByClassName(b),a){for(var d={},f=0,g=0,k;k=c[g];g++)a==k.nodeName&&(d[f++]=k);d.length=f;b=d}else b=c;else if(c=c.getElementsByTagName(a||"*"),b){d={};for(g=f=0;k=c[g];g++)a=k.className,typeof a.split==m&&z(a.split(/\s+/),b)&&(d[f++]=k);d.length=f;b=d}else b=c;return b};
t.hc=function(a,b,c){return Hc(this.ma,arguments)};t.createElement=function(a){return Jc(this.ma,a)};t.createTextNode=function(a){return this.ma.createTextNode(String(a))};t.appendChild=function(a,b){a.appendChild(b)};t.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};var L=function(){this.ua=this.ua;this.Jb=this.Jb};L.prototype.ua=!1;L.prototype.la=function(){this.ua||(this.ua=!0,this.h())};L.prototype.h=function(){if(this.Jb)for(;this.Jb.length;)this.Jb.shift()()};var Nc=function(a){a&&typeof a.la==m&&a.la()};var Oc=!F||9<=Number(Ac),Pc=F&&!zc("9"),Qc=function(){if(!u.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{u.addEventListener("test",Pa,b),u.removeEventListener("test",Pa,b)}catch(c){}return a}();var O=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.ra=!1;this.Ee=!0};O.prototype.stopPropagation=function(){this.ra=!0};O.prototype.preventDefault=function(){this.defaultPrevented=!0;this.Ee=!1};var P=function(a,b){O.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.key="";this.charCode=this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.wa=null;a&&this.Td(a,b)};y(P,O);
P.prototype.Td=function(a,b){var c=this.type=a.type;this.target=a.target||a.srcElement;this.currentTarget=b;if(b=a.relatedTarget){if(G){a:{try{nc(b.nodeName);var d=!0;break a}catch(f){}d=!1}d||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;this.keyCode=a.keyCode||0;this.key=a.key||"";this.charCode=a.charCode||(c==ua?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.wa=a;a.defaultPrevented&&
this.preventDefault()};P.prototype.stopPropagation=function(){P.l.stopPropagation.call(this);this.wa.stopPropagation?this.wa.stopPropagation():this.wa.cancelBubble=!0};P.prototype.preventDefault=function(){P.l.preventDefault.call(this);var a=this.wa;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Pc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Rc="closure_listenable_"+(1E6*Math.random()|0),Sc=function(a){return!(!a||!a[Rc])},Tc=0;var Uc=function(a,b,c,d,f,g){this.listener=a;this.proxy=b;this.src=c;this.type=d;this.capture=!!f;this.wb=g;this.key=++Tc;this.Ea=this.lb=!1};Uc.prototype.Hb=function(){this.Ea=!0;this.wb=this.src=this.proxy=this.listener=null};var Vc=function(a){this.src=a;this.m={};this.fb=0};t=Vc.prototype;t.add=function(a,b,c,d,f){var g=a.toString();a=this.m[g];a||(a=this.m[g]=[],this.fb++);var k=Wc(a,b,d,f);-1<k?(b=a[k],c||(b.lb=!1)):(b=new Uc(b,null,this.src,g,!!d,f),b.lb=c,a.push(b));return b};t.remove=function(a,b,c,d){a=a.toString();if(!(a in this.m))return!1;var f=this.m[a];b=Wc(f,b,c,d);return-1<b?(f[b].Hb(),Array.prototype.splice.call(f,b,1),0==f.length&&(delete this.m[a],this.fb--),!0):!1};
t.ze=function(a){var b=a.type;if(!(b in this.m))return!1;var c=lb(this.m[b],a);c&&(a.Hb(),0==this.m[b].length&&(delete this.m[b],this.fb--));return c};t.Lb=function(a){a=a&&a.toString();var b=0,c;for(c in this.m)if(!a||c==a){for(var d=this.m[c],f=0;f<d.length;f++)++b,d[f].Hb();delete this.m[c];this.fb--}return b};t.Oa=function(a,b,c,d){a=this.m[a.toString()];var f=-1;a&&(f=Wc(a,b,c,d));return-1<f?a[f]:null};
var Wc=function(a,b,c,d){for(var f=0;f<a.length;++f){var g=a[f];if(!g.Ea&&g.listener==b&&g.capture==!!c&&g.wb==d)return f}return-1};var Xc="closure_lm_"+(1E6*Math.random()|0),Yc={},Zc=0,Q=function(a,b,c,d,f){if(d&&d.once)return $c(a,b,c,d,f);if(w(b)){for(var g=0;g<b.length;g++)Q(a,b[g],c,d,f);return null}c=ad(c);return Sc(a)?a.Da(b,c,Ua(d)?!!d.capture:!!d,f):bd(a,b,c,!1,d,f)},bd=function(a,b,c,d,f,g){if(!b)throw Error("Invalid event type");var k=Ua(f)?!!f.capture:!!f,l=cd(a);l||(a[Xc]=l=new Vc(a));c=l.add(b,c,d,k,g);if(c.proxy)return c;d=dd();c.proxy=d;d.src=a;d.listener=c;if(a.addEventListener)Qc||(f=k),void 0===f&&(f=!1),a.addEventListener(b.toString(),
d,f);else if(a.attachEvent)a.attachEvent(ed(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Zc++;return c},dd=function(){var a=fd,b=Oc?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b},$c=function(a,b,c,d,f){if(w(b)){for(var g=0;g<b.length;g++)$c(a,b[g],c,d,f);return null}c=ad(c);return Sc(a)?a.zc(b,c,Ua(d)?!!d.capture:!!d,f):bd(a,b,c,!0,d,
f)},gd=function(a,b,c,d,f){if(w(b)){for(var g=0;g<b.length;g++)gd(a,b[g],c,d,f);return null}d=Ua(d)?!!d.capture:!!d;c=ad(c);if(Sc(a))return a.Rb(b,c,d,f);if(!a)return!1;if(a=cd(a))if(b=a.Oa(b,c,d,f))return hd(b);return!1},hd=function(a){if(typeof a===za||!a||a.Ea)return!1;var b=a.src;if(Sc(b))return b.We(a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(ed(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Zc--;(c=cd(b))?(c.ze(a),
0==c.fb&&(c.src=null,b[Xc]=null)):a.Hb();return!0},id=function(a,b){if(!a)return 0;if(Sc(a))return a.ye(b);a=cd(a);if(!a)return 0;var c=0;b=b&&b.toString();for(var d in a.m)if(!b||d==b)for(var f=a.m[d].concat(),g=0;g<f.length;++g)hd(f[g])&&++c;return c},ed=function(a){return a in Yc?Yc[a]:Yc[a]="on"+a},kd=function(a,b,c,d){var f=!0;if(a=cd(a))if(b=a.m[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var g=b[a];g&&g.capture==c&&!g.Ea&&(g=jd(g,d),f=f&&!1!==g)}return f},jd=function(a,b){var c=a.listener,
d=a.wb||a.src;a.lb&&hd(a);return c.call(d,b)},fd=function(a,b){if(a.Ea)return!0;if(!Oc){if(!b)a:{b=["window","event"];for(var c=u,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new P(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var f=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(k){f=!0}if(f||void 0==d.returnValue)d.returnValue=!0}d=[];for(f=b.currentTarget;f;f=f.parentNode)d.push(f);a=a.type;for(f=d.length-1;!b.ra&&0<=f;f--){b.currentTarget=d[f];var g=kd(d[f],
a,!0,b);c=c&&g}for(f=0;!b.ra&&f<d.length;f++)b.currentTarget=d[f],g=kd(d[f],a,!1,b),c=c&&g}return c}return jd(a,new P(b,this))},cd=function(a){a=a[Xc];return a instanceof Vc?a:null},ld="__closure_events_fn_"+(1E9*Math.random()>>>0),ad=function(a){if(Ta(a))return a;a[ld]||(a[ld]=function(b){return a.handleEvent(b)});return a[ld]};var R=function(){L.call(this);this.fa=new Vc(this);this.Of=this;this.Gc=null};y(R,L);R.prototype[Rc]=!0;t=R.prototype;t.addEventListener=function(a,b,c,d){Q(this,a,b,c,d)};t.removeEventListener=function(a,b,c,d){gd(this,a,b,c,d)};
t.dispatchEvent=function(a){var b=this.Gc;if(b){var c=[];for(var d=1;b;b=b.Gc)c.push(b),++d}b=this.Of;d=a.type||a;if(typeof a===r)a=new O(a,b);else if(a instanceof O)a.target=a.target||b;else{var f=a;a=new O(d,b);Hb(a,f)}f=!0;if(c)for(var g=c.length-1;!a.ra&&0<=g;g--){var k=a.currentTarget=c[g];f=k.sb(d,!0,a)&&f}a.ra||(k=a.currentTarget=b,f=k.sb(d,!0,a)&&f,a.ra||(f=k.sb(d,!1,a)&&f));if(c)for(g=0;!a.ra&&g<c.length;g++)k=a.currentTarget=c[g],f=k.sb(d,!1,a)&&f;return f};
t.h=function(){R.l.h.call(this);this.ye();this.Gc=null};t.Da=function(a,b,c,d){return this.fa.add(String(a),b,!1,c,d)};t.zc=function(a,b,c,d){return this.fa.add(String(a),b,!0,c,d)};t.Rb=function(a,b,c,d){return this.fa.remove(String(a),b,c,d)};t.We=function(a){return this.fa.ze(a)};t.ye=function(a){return this.fa?this.fa.Lb(a):0};
t.sb=function(a,b,c){a=this.fa.m[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,f=0;f<a.length;++f){var g=a[f];if(g&&!g.Ea&&g.capture==b){var k=g.listener,l=g.wb||g.src;g.lb&&this.We(g);d=!1!==k.call(l,c)&&d}}return d&&0!=c.Ee};t.Oa=function(a,b,c,d){return this.fa.Oa(String(a),b,c,d)};var md="StopIteration"in u?u.StopIteration:{message:"StopIteration",stack:""},nd=function(){};nd.prototype.next=function(){throw md;};nd.prototype.ac=function(){return this};var od=function(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};var pd=function(){};pd.prototype.td=null;pd.prototype.Md=function(){return this.td||(this.td=this.Kg())};var qd,rd=function(){};y(rd,pd);rd.prototype.xd=function(){var a=this.Nd();return a?new ActiveXObject(a):new XMLHttpRequest};rd.prototype.Kg=function(){var a={};this.Nd()&&(a[0]=!0,a[1]=!0);return a};
rd.prototype.Nd=function(){if(!this.Rd&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var a=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],b=0;b<a.length;b++){var c=a[b];try{return new ActiveXObject(c),this.Rd=c}catch(d){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return this.Rd};qd=new rd;var sd=function(a,b){this.j={};this.c=[];this.gb=this.b=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.addAll(a)};t=sd.prototype;t.o=function(){return this.b};t.v=function(){this.ob();for(var a=[],b=0;b<this.c.length;b++)a.push(this.j[this.c[b]]);return a};t.L=function(){this.ob();return this.c.concat()};t.ka=function(a){return td(this.j,a)};t.isEmpty=function(){return 0==this.b};
t.clear=function(){this.j={};this.gb=this.b=this.c.length=0};t.remove=function(a){return td(this.j,a)?(delete this.j[a],this.b--,this.gb++,this.c.length>2*this.b&&this.ob(),!0):!1};t.ob=function(){if(this.b!=this.c.length){for(var a=0,b=0;a<this.c.length;){var c=this.c[a];td(this.j,c)&&(this.c[b++]=c);a++}this.c.length=b}if(this.b!=this.c.length){var d={};for(b=a=0;a<this.c.length;)c=this.c[a],td(d,c)||(this.c[b++]=c,d[c]=1),a++;this.c.length=b}};
t.get=function(a,b){return td(this.j,a)?this.j[a]:b};t.set=function(a,b){td(this.j,a)||(this.b++,this.c.push(a),this.gb++);this.j[a]=b};t.addAll=function(a){if(a instanceof sd)for(var b=a.L(),c=0;c<b.length;c++)this.set(b[c],a.get(b[c]));else for(b in a)this.set(b,a[b])};t.forEach=function(a,b){for(var c=this.L(),d=0;d<c.length;d++){var f=c[d],g=this.get(f);a.call(b,g,f,this)}};t.clone=function(){return new sd(this)};
t.ac=function(a){this.ob();var b=0,c=this.gb,d=this,f=new nd;f.next=function(){if(c!=d.gb)throw Error("The map has changed since the iterator was created");if(b>=d.c.length)throw md;var g=d.c[b++];return a?g:d.j[g]};return f};var td=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var ud=function(a){if(a.v&&typeof a.v==m)return a.v();if(typeof a===r)return a.split("");if(Sa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Cb(a)},vd=function(a,b,c){if(a.forEach&&typeof a.forEach==m)a.forEach(b,c);else if(Sa(a)||typeof a===r)fb(a,b,c);else{if(a.L&&typeof a.L==m)var d=a.L();else if(a.v&&typeof a.v==m)d=void 0;else if(Sa(a)||typeof a===r){d=[];for(var f=a.length,g=0;g<f;g++)d.push(g)}else d=Db(a);f=ud(a);g=f.length;for(var k=0;k<g;k++)b.call(c,f[k],d&&d[k],
a)}};var wd=function(a,b,c){if(Ta(a))c&&(a=x(a,c));else if(a&&typeof a.handleEvent==m)a=x(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:u.setTimeout(a,b||0)};var xd=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,yd=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),f=null;if(0<=d){var g=a[c].substring(0,d);f=a[c].substring(d+1)}else g=a[c];b(g,f?decodeURIComponent(f.replace(/\+/g," ")):"")}}};var S=function(a){R.call(this);this.headers=new sd;this.Wb=a||null;this.ba=!1;this.Vb=this.a=null;this.yc="";this.Ca=0;this.pa=this.tc=this.zb=this.mc=!1;this.sa=0;this.Qb=null;this.Fa="";this.Tc=this.xh=this.aa=!1};y(S,R);var zd=/^https?$/i,Ad=["POST","PUT"],Bd=[],Cd=function(a,b,c,d,f,g,k){var l=new S;Bd.push(l);b&&l.Da(e,b);l.zc(Ba,l.Yf);g&&l.Pc(g);k&&l.Qc(k);l.send(a,c,d,f);return l};t=S.prototype;t.Yf=function(){this.la();lb(Bd,this)};t.Pc=function(a){this.sa=Math.max(0,a)};
t.Gh=function(a){this.Fa=a};t.Qc=function(a){this.aa=a};
t.send=function(a,b,c,d){if(this.a)throw Error("[goog.net.XhrIo] Object is active with another request="+this.yc+"; newUri="+a);b=b?b.toUpperCase():"GET";this.yc=a;this.Ca=0;this.mc=!1;this.ba=!0;this.a=this.ag();this.Vb=this.Wb?this.Wb.Md():qd.Md();this.a.onreadystatechange=x(this.pe,this);this.xh&&"onprogress"in this.a&&(this.a.onprogress=x(function(g){this.ne(g,!0)},this),this.a.upload&&(this.a.upload.onprogress=x(this.ne,this)));try{this.tc=!0,this.a.open(b,String(a),!0),this.tc=!1}catch(g){this.Fd(5,
g);return}a=c||"";var f=this.headers.clone();d&&vd(d,function(g,k){f.set(k,g)});d=jb(f.L(),Dd);c=u.FormData&&a instanceof u.FormData;!z(Ad,b)||d||c||f.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");f.forEach(function(g,k){this.a.setRequestHeader(k,g)},this);this.Fa&&(this.a.responseType=this.Fa);"withCredentials"in this.a&&this.a.withCredentials!==this.aa&&(this.a.withCredentials=this.aa);try{this.ud(),0<this.sa&&((this.Tc=Ed(this.a))?(this.a.timeout=this.sa,this.a.ontimeout=
x(this.Ue,this)):this.Qb=wd(this.Ue,this.sa,this)),this.zb=!0,this.a.send(a),this.zb=!1}catch(g){this.Fd(5,g)}};var Ed=function(a){return F&&zc(9)&&typeof a.timeout===za&&void 0!==a.ontimeout},Dd=function(a){return"content-type"==a.toLowerCase()};t=S.prototype;t.ag=function(){return this.Wb?this.Wb.xd():qd.xd()};t.Ue=function(){"undefined"!=typeof Ma&&this.a&&(this.Ca=8,this.dispatchEvent("timeout"),this.abort(8))};
t.Fd=function(a){this.ba=!1;this.a&&(this.pa=!0,this.a.abort(),this.pa=!1);this.Ca=a;this.Cd();this.nb()};t.Cd=function(){this.mc||(this.mc=!0,this.dispatchEvent(e),this.dispatchEvent("error"))};t.abort=function(a){this.a&&this.ba&&(this.ba=!1,this.pa=!0,this.a.abort(),this.pa=!1,this.Ca=a||7,this.dispatchEvent(e),this.dispatchEvent("abort"),this.nb())};t.h=function(){this.a&&(this.ba&&(this.ba=!1,this.pa=!0,this.a.abort(),this.pa=!1),this.nb(!0));S.l.h.call(this)};
t.pe=function(){this.ua||(this.tc||this.zb||this.pa?this.oe():this.rh())};t.rh=function(){this.oe()};t.oe=function(){if(this.ba&&"undefined"!=typeof Ma&&(!this.Vb[1]||4!=this.ub()||2!=this.getStatus()))if(this.zb&&4==this.ub())wd(this.pe,0,this);else if(this.dispatchEvent("readystatechange"),this.Ng()){this.ba=!1;try{this.Xa()?(this.dispatchEvent(e),this.dispatchEvent(Ja)):(this.Ca=6,this.Cd())}finally{this.nb()}}};
t.ne=function(a,b){this.dispatchEvent(Fd(a,"progress"));this.dispatchEvent(Fd(a,b?"downloadprogress":"uploadprogress"))};var Fd=function(a,b){return{type:b,lengthComputable:a.lengthComputable,loaded:a.loaded,total:a.total}};t=S.prototype;t.nb=function(a){if(this.a){this.ud();var b=this.a,c=this.Vb[0]?Pa:null;this.Vb=this.a=null;a||this.dispatchEvent(Ba);try{b.onreadystatechange=c}catch(d){}}};t.ud=function(){this.a&&this.Tc&&(this.a.ontimeout=null);this.Qb&&(u.clearTimeout(this.Qb),this.Qb=null)};
t.Bb=function(){return!!this.a};t.Ng=function(){return 4==this.ub()};t.Xa=function(){var a=this.getStatus();a:switch(a){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var b=!0;break a;default:b=!1}return b||0===a&&!this.Og()};t.Og=function(){var a=String(this.yc).match(xd)[1]||null;!a&&u.self&&u.self.location&&(a=u.self.location.protocol,a=a.substr(0,a.length-1));return zd.test(a?a.toLowerCase():"")};t.ub=function(){return this.a?this.a.readyState:0};
t.getStatus=function(){try{return 2<this.ub()?this.a.status:-1}catch(a){return-1}};t.sg=function(){try{return this.a?this.a.responseText:""}catch(a){return""}};t.Od=function(a){if(this.a){var b=this.a.responseText;a&&0==b.indexOf(a)&&(b=b.substring(a.length));a:{a=b;if(u.JSON)try{var c=u.JSON.parse(a);break a}catch(d){}c=od(a)}return c}};
t.rg=function(){try{if(!this.a)return null;if("response"in this.a)return this.a.response;switch(this.Fa){case "":case "text":return this.a.responseText;case "arraybuffer":if("mozResponseArrayBuffer"in this.a)return this.a.mozResponseArrayBuffer}return null}catch(a){return null}};var Gd=function(){};Gd.prototype.X=function(){return"NONE"};Gd.prototype.qa=function(){return null};Gd.prototype.Wd=function(){return!1};var Hd=function(a){this.label=a};y(Hd,Gd);Hd.prototype.S=function(){return this.label};var T=function(a,b,c){this.label=b;this.value=a.X();this.Mg=c;this.nc=a};y(T,Gd);t=T.prototype;t.S=function(){return this.label};t.X=function(){return this.value};t.Wd=function(){return this.Mg};t.encode=function(){return this.nc.encode()+"="};t.qa=function(){return new Id(this)};var Jd=function(){};y(Jd,Gd);Jd.prototype.encode=function(){return encodeURIComponent(this.X())};Jd.prototype.qa=function(){return null};var Kd=function(a){T.call(this,a,a.S(),!0)};y(Kd,T);var Ld=function(){};y(Ld,Jd);Ld.prototype.S=function(){return"Anonymous"};Ld.prototype.X=function(){return"ANON"};Ld.prototype.decode=function(){return new Kd(this)};var Md=function(a,b){this.pb=this.Uc=this.Ga="";this.Kb=null;this.Ma=this.re="";this.F=this.Pg=!1;var c;a instanceof Md?(this.F=void 0!==b?b:a.F,this.Oe(a.Ga),this.Re(a.Uc),this.Ie(a.pb),this.Me(a.Kb),this.setPath(a.getPath()),this.Ne(a.ha.clone()),this.Ke(a.Ma)):a&&(c=String(a).match(xd))?(this.F=!!b,this.Oe(c[1]||"",!0),this.Re(c[2]||"",!0),this.Ie(c[3]||"",!0),this.Me(c[4]),this.setPath(c[5]||"",!0),this.Ne(c[6]||"",!0),this.Ke(c[7]||"",!0)):(this.F=!!b,this.ha=new Nd(null,null,this.F))};t=Md.prototype;
t.toString=function(){var a=[],b=this.Ga;b&&a.push(Od(b,Pd,!0),":");var c=this.pb;if(c||"file"==b)a.push("//"),(b=this.Uc)&&a.push(Od(b,Pd,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.Kb,null!=c&&a.push(":",String(c));if(c=this.getPath())this.Dg()&&"/"!=c.charAt(0)&&a.push("/"),a.push(Od(c,"/"==c.charAt(0)?Qd:Rd,!0));(c=this.lg())&&a.push("?",c);(c=this.Ma)&&a.push("#",Od(c,Sd));return a.join("")};t.clone=function(){return new Md(this)};
t.Oe=function(a,b){this.ea();if(this.Ga=b?Td(a,!0):a)this.Ga=this.Ga.replace(/:$/,"");return this};t.Re=function(a,b){this.ea();this.Uc=b?Td(a):a;return this};t.Ie=function(a,b){this.ea();this.pb=b?Td(a,!0):a;return this};t.Dg=function(){return!!this.pb};t.Me=function(a){this.ea();if(a){a=Number(a);if(isNaN(a)||0>a)throw Error("Bad port number "+a);this.Kb=a}else this.Kb=null;return this};t.getPath=function(){return this.re};t.setPath=function(a,b){this.ea();this.re=b?Td(a,!0):a;return this};
t.Ne=function(a,b){this.ea();a instanceof Nd?(this.ha=a,this.ha.Oc(this.F)):(b||(a=Od(a,Ud)),this.ha=new Nd(a,null,this.F));return this};t.lg=function(){return this.ha.toString()};t.Ob=function(a,b){this.ea();this.ha.set(a,b);return this};t.Ke=function(a,b){this.ea();this.Ma=b?Td(a):a;return this};t.ea=function(){if(this.Pg)throw Error("Tried to modify a read-only Uri");};t.Oc=function(a){this.F=a;this.ha&&this.ha.Oc(a);return this};
var Td=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},Od=function(a,b,c){return typeof a===r?(a=encodeURI(a).replace(b,Vd),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},Vd=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Pd=/[#\/\?@]/g,Rd=/[#\?:]/g,Qd=/[#\?]/g,Ud=/[#\?@]/g,Sd=/#/g,Nd=function(a,b,c){this.b=this.g=null;this.da=a||null;this.F=!!c};t=Nd.prototype;
t.P=function(){if(!this.g&&(this.g=new sd,this.b=0,this.da)){var a=this;yd(this.da,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g," ")),c)})}};t.o=function(){this.P();return this.b};t.add=function(a,b){this.P();this.Ba();a=this.ya(a);var c=this.g.get(a);c||this.g.set(a,c=[]);c.push(b);this.b+=1;return this};t.remove=function(a){this.P();a=this.ya(a);return this.g.ka(a)?(this.Ba(),this.b-=this.g.get(a).length,this.g.remove(a)):!1};t.clear=function(){this.Ba();this.g=null;this.b=0};
t.isEmpty=function(){this.P();return 0==this.b};t.ka=function(a){this.P();a=this.ya(a);return this.g.ka(a)};t.forEach=function(a,b){this.P();this.g.forEach(function(c,d){fb(c,function(f){a.call(b,f,d,this)},this)},this)};t.L=function(){this.P();for(var a=this.g.v(),b=this.g.L(),c=[],d=0;d<b.length;d++)for(var f=a[d],g=0;g<f.length;g++)c.push(b[d]);return c};
t.v=function(a){this.P();var b=[];if(typeof a===r)this.ka(a)&&(b=mb(b,this.g.get(this.ya(a))));else{a=this.g.v();for(var c=0;c<a.length;c++)b=mb(b,a[c])}return b};t.set=function(a,b){this.P();this.Ba();a=this.ya(a);this.ka(a)&&(this.b-=this.g.get(a).length);this.g.set(a,[b]);this.b+=1;return this};t.get=function(a,b){if(!a)return b;a=this.v(a);return 0<a.length?String(a[0]):b};t.setValues=function(a,b){this.remove(a);0<b.length&&(this.Ba(),this.g.set(this.ya(a),nb(b)),this.b+=b.length)};
t.toString=function(){if(this.da)return this.da;if(!this.g)return"";for(var a=[],b=this.g.L(),c=0;c<b.length;c++){var d=b[c],f=encodeURIComponent(String(d));d=this.v(d);for(var g=0;g<d.length;g++){var k=f;""!==d[g]&&(k+="="+encodeURIComponent(String(d[g])));a.push(k)}}return this.da=a.join("&")};t.Ba=function(){this.da=null};t.clone=function(){var a=new Nd;a.da=this.da;this.g&&(a.g=this.g.clone(),a.b=this.b);return a};t.ya=function(a){a=String(a);this.F&&(a=a.toLowerCase());return a};
t.Oc=function(a){a&&!this.F&&(this.P(),this.Ba(),this.g.forEach(function(b,c){var d=c.toLowerCase();c!=d&&(this.remove(c),this.setValues(d,b))},this));this.F=a};var Wd="";var Xd=function(){"loading"!=document.readyState?this.Ud():Q(window,"load",this.Ud)};Xd.prototype.Ud=function(){var a=Array.prototype.slice.call(document.getElementsByTagName("link"),0);var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];a=b?b.call(a):{next:La(a)};for(b=a.next();!b.done;b=a.next())b=b.value,b.getAttribute("data-async-css")==Ka&&b.getAttribute("media")==n&&b.setAttribute("media","all")};var Yd=function(a){return typeof a.className==r?a.className:a.getAttribute&&a.getAttribute("class")||""},Zd=function(a){return a.classList?a.classList:Yd(a).match(/\S+/g)||[]},$d=function(a,b){typeof a.className==r?a.className=b:a.setAttribute&&a.setAttribute("class",b)},ae=function(a,b){return a.classList?a.classList.contains(b):z(Zd(a),b)},be=function(a,b){if(a.classList)a.classList.add(b);else if(!ae(a,b)){var c=Yd(a);$d(a,c+(0<c.length?" "+b:b))}},ce=function(a,b){a.classList?a.classList.remove(b):
ae(a,b)&&$d(a,gb(Zd(a),function(c){return c!=b}).join(" "))};var de=function(a){var b=a.offsetWidth,c=a.offsetHeight,d=H&&!b&&!c;if((void 0===b||d)&&a.getBoundingClientRect){a:{try{var f=a.getBoundingClientRect()}catch(g){f={left:0,top:0,right:0,bottom:0};break a}F&&a.ownerDocument.body&&(a=a.ownerDocument,f.left-=a.documentElement.clientLeft+a.body.clientLeft,f.top-=a.documentElement.clientTop+a.body.clientTop)}return new Cc(f.right-f.left,f.bottom-f.top)}return new Cc(b,c)},ee=function(a,b){a.style.display=b?"":n},ge=function(a,b){b=Ec(b);var c=b.ma;if(F&&
c.createStyleSheet)return b=c.createStyleSheet(),fe(b,a),b;c=b.Hd("HEAD")[0];if(!c){var d=b.Hd("BODY")[0];c=b.hc("HEAD");d.parentNode.insertBefore(c,d)}d=b.hc("STYLE");fe(d,a);b.appendChild(c,d);return d},fe=function(a,b){b=hc(b);F&&void 0!==a.cssText?a.cssText=b:a.innerHTML=b};/*

 CC0 1.0 Universal License
 Public Domain Dedication

 The person(s) who associated a work with this deed has dedicated the work to
 the public domain by waiving all of his or her rights to the work worldwide
 under copyright law, including all related and neighboring rights, to the
 extent allowed by law.

 You can copy, modify, distribute and perform the work, even for commercial
 purposes, all without asking permission.

 In no way are the patent or trademark rights of any person affected by CC0,
 nor are the rights that other persons may have in the work or in how the work
 is used, such as publicity or privacy rights.

 Unless expressly stated otherwise, the person(s) who associated a work with
 this deed makes no warranties about the work, and disclaims liability for all
 uses of the work, to the fullest extent permitted by applicable law.

 When using or citing the work, you should not imply endorsement by the author
 or the affirmer.

 This is a human-readable summary of the Legal Code (read the full text).
 svg4everybody v2.1.8 | github.com/jonathantneal/svg4everybody */
function he(a,b,c){if(c){var d=document.createDocumentFragment(),f=!b.hasAttribute("viewBox")&&c.getAttribute("viewBox");f&&b.setAttribute("viewBox",f);for(b=c.cloneNode(!0);b.childNodes.length;)d.appendChild(b.firstChild);a.appendChild(d)}}
function ie(a){a.onreadystatechange=function(){if(4===a.readyState){var b=a.Nf;b||(b=a.Nf=document.implementation.createHTMLDocument(""),b.body.innerHTML=a.responseText,a.gd={});a.hd.splice(0).map(function(c){var d=a.gd[c.id];d||(d=a.gd[c.id]=b.getElementById(c.id));he(c.parent,c.Jh,d)})}};a.onreadystatechange()}function je(){return"undefined"!=typeof LEGACY_SUPPORT&&LEGACY_SUPPORT}
var ne=function(a){function b(){for(var na=0;na<zb.length;){var I=zb[na],db=I.parentNode,E;for(E=db;"svg"!==E.nodeName.toLowerCase()&&(E=E.parentNode,E););if(E){var M=I.getAttribute("xlink:href")||I.getAttribute("href");!M&&c.attributeName&&(M=I.getAttribute(c.attributeName));if(je()&&f){var J=document.createElement("img");J.style.cssText="display:inline-block;height:100%;width:100%";J.setAttribute("width",E.getAttribute("width")||E.clientWidth);J.setAttribute("height",E.getAttribute("height")||E.clientHeight);
J.src=d(M,E,I);db.replaceChild(J,I)}else ke&&(!c.Lh||c.Lh(M,E,I)?(db.removeChild(I),M=M.split("#"),I=M.shift(),M=M.join("#"),I.length?(J=le[I],J||(J=le[I]=new XMLHttpRequest,J.open("GET",I),J.send(),J.hd=[]),J.hd.push({parent:db,Jh:E,id:M}),ie(J)):he(db,E,document.getElementById(M))):(++na,++me))}else++na}if(!zb.length||0<zb.length-me)window.requestAnimationFrame?window.requestAnimationFrame(b):setTimeout(b,67)}var c=Object(a);if(je()){var d=c.Qh||function(na){return na.replace(/\?[^#]+/,"").replace("#",
".").replace(/^\./,"")+".png"+(/\?[^#]+/.exec(na)||[""])[0]};var f="nosvg"in c?c.Sh:/\bMSIE [1-8]\b/.test(navigator.userAgent)}a=/\bMSIE [1-8]\.0\b/;var g=/\bTrident\/[567]\b|\bMSIE (?:9|10)\.0\b/,k=/\bAppleWebKit\/(\d+)\b/,l=/\bEdge\/12\.(\d+)\b/,q=/\bEdge\/.(\d+)\b/,N=window.top!==window.self;var ke="polyfill"in c?c.Uh:je()?a.test(navigator.userAgent)||g.test(navigator.userAgent)||10547>(navigator.userAgent.match(l)||[])[1]||537>(navigator.userAgent.match(k)||[])[1]||q.test(navigator.userAgent)&&
N:g.test(navigator.userAgent)||10547>(navigator.userAgent.match(l)||[])[1]||537>(navigator.userAgent.match(k)||[])[1]||q.test(navigator.userAgent)&&N;var le={},zb=document.getElementsByTagName("use"),me=0;ke&&b()};var oe=function(a){return/^[A-Za-z0-9]+$/.test(a)||/^#[0-9A-Fa-f]{3}$/.test(a)||/^#[0-9A-Fa-f]{6}$/.test(a)||/^rgb *\( *\d{1,3}%? *, *\d{1,3}%? *, *\d{1,3}%? *\)$/.test(a)||/^rgba *\( *\d{1,3}%? *, *\d{1,3}%? *, *\d{1,3}%? *, *\d{1,3}%? *\)$/.test(a)},pe=function(a){a=a.split(",");for(var b=0;b<a.length;b++){var c=a[b];c=pb(c);if(!(/^[- A-Za-z0-9]*$/.test(c)||/^"[- A-Za-z0-9]*"$/.test(c)||/^'[- A-Za-z0-9]*'$/.test(c)))return!1}return!0},qe=function(){if(window.parent&&window.parent.postMessage){var a=
document.getElementById("previewHolder"),b=0;if(a){b:{b=9==a.nodeType?a:a.ownerDocument||a.document;if(b.defaultView&&b.defaultView.getComputedStyle&&(b=b.defaultView.getComputedStyle(a,null))){b=b.display||b.getPropertyValue("display")||"";break b}b=""}if((b||(a.currentStyle?a.currentStyle.display:null)||a.style&&a.style.display)!=n)a=de(a);else{b=a.style;var c=b.display,d=b.visibility,f=b.position;b.visibility=pa;b.position="absolute";b.display="inline";a=de(a);b.display=c;b.position=f;b.visibility=
d}b=a.height}a=document.getElementById(da);c=0;a&&(c=a.offsetHeight);b=(b=Math.max(b,c||document.body.offsetHeight))||230;a="amp=1"==(new Md(document.location.href)).Ma?{sentinel:"amp",type:"embed-size",height:b}:"set-comment-editor-height "+b+"px";window.parent.postMessage(a,"*")}},re=function(){var a=document.getElementById(ia),b=document.getElementById(Aa),c=document.getElementById("postCommentPreview"),d=function(){b&&(b.disabled=""==a.value);c&&(c.disabled=""==a.value)};a&&"oninput"in a&&(d(null),
Q(a,ta,d))},se=function(a){var b=[];F&&b.push(gc(".previewMode .postCommentButtonHolder",{"padding-top":"22px"}));var c=(new Md(a)).Ma;if(0!=c.length){a=null;try{c=decodeURIComponent(c),a=JSON.parse(c)}catch(k){}if(a&&a.color){c=lc(kc(a.color));var d=lc(kc(a.unvisitedLinkColor));a=lc(kc(a.fontFamily));oe(c)&&oe(d)&&pe(a)&&(b.push(gc("body",{color:c,"font-family":a})),b.push(gc("a:link, a:visited, a:active, a:hover",{color:d})))}}ge(ic(b));setTimeout(qe,100);var f=K(da);if((b=K(ia))&&f){var g=!1;Q(b,
"focus",function(){g||(g=!0,ce(f,"compact"),qe())})}ne();new Xd};var te=function(a){a=K(a);var b=a.nodeName.toLowerCase();a.style.display="span"==b||"img"==b||"a"==b||b==ta||"select"==b?"inline":"block"},U=function(a){K(a).style.display=n};var V=function(a,b,c){var d;c&&U(xa);switch(a){case 0:a=d="captcha-error";break;case 1:a=d="id-error";break;case 2:case 3:case 4:a="main-error";d="main-error-holder";break;case 5:a=d="nameUrlDialogErrorHolder";break;default:throw Error("internal error in show message");}c?(K(a).innerHTML=b,te(d),K(ia).className="commentBody-err"):(Mc(K(a)),U(d));qe()},ue=function(a){V(3,null,!1);K("main-status").innerHTML=a;te(xa);qe()};var ve=function(){};ve.prototype.Ih=function(){U(sa);K(ia).disabled=!0;K(Aa).disabled=!0};ve.prototype.Eg=function(){te(sa);K(ia).disabled=!1;K(Aa).disabled=!1};var Id=function(a){this.oa=a};y(Id,ve);t=Id.prototype;t.Wa=function(){return!1};t.Pb=function(){if(!this.Wa())throw Error("Trying to show a non-editable identity");this.Ih();te(ra)};t.$d=function(){return!0};t.Rc=function(){if(!this.Wa())throw Error("Trying to show edit button for a non-editable identity");te("editButton")};t.te=function(){};t.Nc=function(){};t.Qa=function(){U(ra);U("editButton");U("settingsButton");U("commentDash");U(Ia);this.Eg()};var we=function(a){a=a.className;return typeof a===r&&a.match(/\S+/g)||[]},xe=function(a,b){for(var c=we(a),d=ob(arguments,1),f=c.length+d.length,g=0;g<d.length;g++)z(c,d[g])||c.push(d[g]);a.className=c.join(" ");return c.length==f},ze=function(a,b){var c=we(a),d=ob(arguments,1),f=ye(c,d);a.className=f.join(" ");return f.length==c.length-d.length},ye=function(a,b){return gb(a,function(c){return!z(b,c)})};var Ce=function(a){for(var b=[],c=Ae,d=a.elements,f,g=0;f=d.item(g);g++)if(f.form==a&&!f.disabled&&"FIELDSET"!=f.tagName){var k=f.name;switch(f.type.toLowerCase()){case "file":case "submit":case "reset":case "button":break;case Ea:f=Be(f);if(null!=f)for(var l,q=0;l=f[q];q++)c(b,k,l);break;default:l=Be(f),null!=l&&c(b,k,l)}}d=a.getElementsByTagName("INPUT");for(g=0;f=d[g];g++)f.form==a&&"image"==f.type.toLowerCase()&&(k=f.name,c(b,k,f.value),c(b,k+".x","0"),c(b,k+".y","0"));return b.join("&")},Ae=
function(a,b,c){a.push(encodeURIComponent(b)+"="+encodeURIComponent(c))},Be=function(a){var b=a.type;if(typeof b===r)switch(b.toLowerCase()){case "checkbox":case "radio":return a.checked?a.value:null;case "select-one":return b=a.selectedIndex,0<=b?a.options[b].value:null;case Ea:b=[];for(var c,d=0;c=a.options[d];d++)c.selected&&b.push(c.value);return b.length?b:null}return null!=a.value?a.value:null};var De=!1,Ee=!1,Fe=!1,Ge=function(a,b){Ee=a;Fe=b;window.parent==window.top&&(a||b)?(a=K(Ia),b?xe(a,"checked"):ze(a,"checked"),te(Ia),K("ajaxAction").value=b?"UnsubscribeByEmail":"SubscribeByEmail"):U(Ia)};var Ie=function(a,b){T.call(this,new He,a,!1);this.kg=b};y(Ie,T);Ie.prototype.encode=function(){return this.nc.encode()+"="+this.label+"="+this.kg};Ie.prototype.S=function(){return this.label+" (Google)"};Ie.prototype.qa=function(){return new Je(this)};var He=function(){};y(He,Jd);He.prototype.S=function(){return""};He.prototype.X=function(){return"CURRENT"};He.prototype.decode=function(a){return new Ie(a[1],a[2])};He.prototype.qa=function(){throw Error("internal error");};
var Je=function(a){this.oa=a};y(Je,Id);Je.prototype.Rc=function(){(Ee||Fe)&&te(Ia)};var Ke=function(a){T.call(this,a,a.S(),!1)};y(Ke,T);var Le=function(){};y(Le,Jd);Le.prototype.S=function(){return"Google Account"};Le.prototype.X=function(){return"GOOGLE"};Le.prototype.decode=function(){return this.Ld()};Le.prototype.Ld=function(){return new Ke(this)};var Me=function(a,b,c){T.call(this,a,null,!0);this.name=b;this.url=c};y(Me,T);Me.prototype.S=function(){return this.name+" ("+this.url+")"};Me.prototype.encode=function(){return this.nc.encode()+"="+encodeURIComponent(this.name)+"="+encodeURIComponent(this.url)};Me.prototype.qa=function(){return new Ne(this)};var Oe=function(){};y(Oe,Jd);Oe.prototype.S=function(){return"Name/URL"};Oe.prototype.X=function(){return"NAMEURL"};Oe.prototype.qa=function(){return new Ne(new Me(this,"",""))};
Oe.prototype.decode=function(a){return new Me(this,a[1],a[2])};var Ne=function(a){this.oa=a};y(Ne,Id);t=Ne.prototype;t.Wa=function(){return!0};t.Pb=function(){Ne.l.Pb.call(this);te(ya)};t.Qa=function(){Ne.l.Qa.call(this);U(ya);V(5,null,!1);this.Le("");this.Qe("")};t.te=function(){this.Le(this.oa.name);this.Qe(this.oa.url)};t.Nc=function(){Ne.l.Nc.call(this);this.oa.name=this.Kd();this.oa.url=this.ug();this.Rc()};t.$d=function(){return""==this.Kd()?(V(5,"Name should not be empty",!0),!1):!0};
t.Kd=function(){return K("anonNameField").value};t.Le=function(a){K("anonNameField").value=a};t.ug=function(){return K("anonUrlField").value};t.Qe=function(a){K("anonUrlField").value=a};var Pe=function(){this.na=[];this.Za=[];this.Ja=[];this.Ta=[];this.i=this.B=null;this.H=[]};t=Pe.prototype;t.Ab=function(a,b,c,d){for(var f=0;f<this.H.length;f++)if(a==this.H[f])return d(a);d=a.encode();for(f=0;f<this.H.length;f++)if(this.H[f].encode()==d)return c(this.H[f]);return b(a)};t.Jg=function(a){return this.Ab(a,x(function(b){return this.H[this.H.length]=b},this),Jb,Jb)};t.Cb=function(a){function b(){return!1}return this.Ab(a,function(){return!0},b,b)};
t.Va=function(a){function b(){throw Error("item should have been unique");}this.Ab(a,Pa,b,b);return this.Jg(a)};t.cc=function(a){return this.Ab(a,x(function(b){this.H[this.H.length]=b;return this.na[this.na.length]=b},this),Jb,Jb)};t.he=function(){for(var a=document.getElementById("identityControlsHolder"),b=Zd(a),c=0;c<b.length;c++)b[c].slice(0,14)==qa&&ce(a,b[c]);(b=this.Ta[K(sa).selectedIndex])&&be(a,qa+b.value)};t.ld=function(a){this.B=this.cc(a);this.ab();this.Ia();this.kb(!1);return this.B};
t.md=function(a){this.Va(a);this.Za[this.Za.length]=a};t.Rf=function(){var a=this.Va(new Le);this.md(a.Ld())};t.Qf=function(){var a=new Oe;this.Va(a);this.Ja[this.Ja.length]=a};t.Pf=function(){var a=this.Va(new Ld);a=this.Va(new Kd(a));this.Ja[this.Ja.length]=a};t.Ia=function(){var a=this.Ta[K(sa).selectedIndex];if(a.constructor==Hd)this.ab();else{V(1,null,!1);this.i=a.qa();null!=this.i&&this.i.te();this.he();var b=K("anonymousWarning");b&&(ee(b,a.Wd()),qe())}};
t.kb=function(a){if(null!=this.i){var b=this.i.oa;if(a&&this.i.Wa()&&this.Cb(b)||!this.i.$d())this.i.Pb();else return this.i.Nc(),this.i.Qa(),this.i.Wa()&&this.i.Rc(),this.i=null,b}return null};t.Ah=function(){this.cg(K("encodedIds").value);this.B=this.zd(K(la).value);null==this.B&&0<this.na.length&&(this.B=this.na[0]);null==this.B&&1==this.Za.length&&(this.B=this.Za[0]);this.ab();null!=this.B&&(this.Ia(),this.kb(!1))};
t.nd=function(a,b){this.Ta[this.Ta.length]=b;var c=document.createElement("option");c.text=b.S();c.value=b.X();try{a.add(c,null)}catch(d){a.add(c)}this.B==b&&(c.selected=!0);return c};t.dc=function(a,b){for(var c=0;c<b.length;c++)this.nd(a,b[c])};t.ab=function(){for(var a=K(sa);0!=a.options.length;)a.remove(0);this.Ta=[];this.nd(a,new Hd("Select profile...")).disabled="disabled";this.dc(a,this.na);this.dc(a,this.Za);this.dc(a,this.Ja)};
t.hg=function(){for(var a=[],b=0;b<this.na.length;b++)a[a.length]=this.na[b].encode();return a.join("&")};t.cg=function(a){if(""!=a){a=a.split("&");for(var b=0;b<a.length;b++)this.zd(a[b])}};t.zd=function(a){if(""==a)return null;a=a.split("=");for(var b=0;b<a.length;b++)a[b]=decodeURIComponent(a[b]);b=this.jg(a[0]);return null!=b?(a=b.decode(a),this.cc(a)):null};t.jg=function(a){for(var b=0;b<this.H.length;b++)if(this.H[b].encode()==a)return this.H[b];return null};
t.Ze=function(){var a=K(ia).value;if(""==a)return V(2,"Comment should not be empty",!0),!1;if(1E6<a.length)return V(2,"Content length exceeds 1MB. Please abridge.",!0),!1;V(2,null,!1);return!0};t.Ec=function(){null!=this.i&&this.i.Qa();this.Ia();var a=this.kb(!0);null!=a&&(this.B=a)};t.hh=function(){var a=this.kb(!1);null!=a&&this.ld(a)};t.gh=function(){null!=this.i&&(this.i.Qa(),this.i=null);this.ab();this.Ec()};
t.qe=function(){if(null==this.B||"NONE"==this.B.X())return V(1,"Please choose a profile",!0),!1;if(null!=this.i)return!1;K("encodedIds").value=this.hg();K(la).value=this.B.encode();return!0};t.jh=function(){this.B&&(this.Ia(),this.i.Pb())};t.ph=function(){this.Ze()&&this.qe()&&this.Dd(!1)};t.qh=function(){this.Ze()&&this.qe()&&this.Dd(!0)};t.Dd=function(a){K(Fa).value=a?Ka:"false";this.Ia();a=K("commentForm");a.onsubmit();a.submit()};var Qe=function(){ze(K(da),"previewMode");return!0};var Re;Ib("A AREA BUTTON HEAD INPUT LINK MENU META OPTGROUP OPTION PROGRESS STYLE SELECT SOURCE TEXTAREA TITLE TRACK".split(" "));var Se=function(a,b,c){L.call(this);this.Ac=a;this.Lg=b||0;this.za=c;this.Vf=x(this.eg,this)};y(Se,L);t=Se.prototype;t.Ra=0;t.h=function(){Se.l.h.call(this);this.stop();delete this.Ac;delete this.za};t.start=function(a){this.stop();this.Ra=wd(this.Vf,void 0!==a?a:this.Lg)};t.stop=function(){this.Bb()&&u.clearTimeout(this.Ra);this.Ra=0};t.Bb=function(){return 0!=this.Ra};t.eg=function(){this.Ra=0;this.Ac&&this.Ac.call(this.za)};var Te=function(a){L.call(this);this.za=a;this.c={}};y(Te,L);var Ue=[];t=Te.prototype;t.Da=function(a,b,c,d){return this.Rg(a,b,c,d)};t.Rg=function(a,b,c,d,f){w(b)||(b&&(Ue[0]=b.toString()),b=Ue);for(var g=0;g<b.length;g++){var k=Q(a,b[g],c||this.handleEvent,d||!1,f||this.za||this);if(!k)break;this.c[k.key]=k}return this};t.zc=function(a,b,c,d){return this.ge(a,b,c,d)};
t.ge=function(a,b,c,d,f){if(w(b))for(var g=0;g<b.length;g++)this.ge(a,b[g],c,d,f);else{a=$c(a,b,c||this.handleEvent,d,f||this.za||this);if(!a)return this;this.c[a.key]=a}return this};t.Rb=function(a,b,c,d,f){if(w(b))for(var g=0;g<b.length;g++)this.Rb(a,b[g],c,d,f);else c=c||this.handleEvent,d=Ua(d)?!!d.capture:!!d,f=f||this.za||this,c=ad(c),d=!!d,b=Sc(a)?a.Oa(b,c,d,f):a?(a=cd(a))?a.Oa(b,c,d,f):null:null,b&&(hd(b),delete this.c[b.key]);return this};
t.Lb=function(){Bb(this.c,function(a,b){this.c.hasOwnProperty(b)&&hd(a)},this);this.c={}};t.h=function(){Te.l.h.call(this);this.Lb()};t.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var Xe=function(a,b,c,d,f,g){if(H&&!zc("525"))return!0;if(rc&&f)return Ve(a);if(f&&!d)return!1;if(!G){typeof b===za&&(b=We(b));var k=17==b||18==b||rc&&91==b;if((!c||rc)&&k||rc&&16==b&&(d||g))return!1}if((H||qc)&&d&&c)switch(a){case 220:case 219:case 221:case 192:case 186:case 189:case 187:case 188:case 190:case 191:case 192:case 222:return!1}if(F&&d&&b==a)return!1;switch(a){case 13:return G?g||f?!1:!(c&&d):!0;case 27:return!(H||qc||G)}return G&&(d||f||g)?!1:Ve(a)},Ve=function(a){if(48<=a&&57>=a||
96<=a&&106>=a||65<=a&&90>=a||(H||qc)&&0==a)return!0;switch(a){case 32:case 43:case 63:case 64:case 107:case 109:case 110:case 111:case 186:case 59:case 189:case 187:case 61:case 188:case 190:case 191:case 192:case 222:case 219:case 220:case 221:case 163:case 58:return!0;case 173:return G;default:return!1}},We=function(a){if(G)a=Ye(a);else if(rc&&H)switch(a){case 93:a=91}return a},Ye=function(a){switch(a){case 61:return 187;case 59:return 186;case 173:return 189;case 224:return 91;case 0:return 224;
default:return a}};var Ze=function(a,b){R.call(this);a&&this.pd(a,b)};y(Ze,R);t=Ze.prototype;t.va=null;t.Db=null;t.vc=null;t.Eb=null;t.D=-1;t.Z=-1;t.ec=!1;
var $e={3:13,12:144,63232:38,63233:40,63234:37,63235:39,63236:112,63237:113,63238:114,63239:115,63240:116,63241:117,63242:118,63243:119,63244:120,63245:121,63246:122,63247:123,63248:44,63272:46,63273:36,63275:35,63276:33,63277:34,63289:144,63302:45},af={Up:38,Down:40,Left:37,Right:39,Enter:13,F1:112,F2:113,F3:114,F4:115,F5:116,F6:117,F7:118,F8:119,F9:120,F10:121,F11:122,F12:123,"U+007F":46,Home:36,End:35,PageUp:33,PageDown:34,Insert:45},bf=!H||zc("525"),cf=rc&&G;t=Ze.prototype;
t.Ag=function(a){(H||qc)&&(17==this.D&&!a.ctrlKey||18==this.D&&!a.altKey||rc&&91==this.D&&!a.metaKey)&&this.Ce();-1==this.D&&(a.ctrlKey&&17!=a.keyCode?this.D=17:a.altKey&&18!=a.keyCode?this.D=18:a.metaKey&&91!=a.keyCode&&(this.D=91));bf&&!Xe(a.keyCode,this.D,a.shiftKey,a.ctrlKey,a.altKey,a.metaKey)?this.handleEvent(a):(this.Z=We(a.keyCode),cf&&(this.ec=a.altKey))};t.Ce=function(){this.Z=this.D=-1};t.Bg=function(a){this.Ce();this.ec=a.altKey};
t.handleEvent=function(a){var b=a.wa,c=b.altKey;if(F&&a.type==ua){var d=this.Z;var f=13!=d&&27!=d?b.keyCode:0}else(H||qc)&&a.type==ua?(d=this.Z,f=0<=b.charCode&&63232>b.charCode&&Ve(d)?b.charCode:0):pc&&!H?(d=this.Z,f=Ve(d)?b.keyCode:0):(a.type==ua?(cf&&(c=this.ec),b.keyCode==b.charCode?32>b.keyCode?(d=b.keyCode,f=0):(d=this.Z,f=b.charCode):(d=b.keyCode||this.Z,f=b.charCode||0)):(d=b.keyCode||this.Z,f=b.charCode||0),rc&&63==f&&224==d&&(d=191));var g=d=We(d);d?63232<=d&&d in $e?g=$e[d]:25==d&&a.shiftKey&&
(g=9):b.keyIdentifier&&b.keyIdentifier in af&&(g=af[b.keyIdentifier]);G&&bf&&a.type==ua&&!Xe(g,this.D,a.shiftKey,a.ctrlKey,c,a.metaKey)||(a=g==this.D,this.D=g,b=new df(g,f,a,b),b.altKey=c,this.dispatchEvent(b))};t.Na=function(){return this.va};t.pd=function(a,b){this.Eb&&this.detach();this.va=a;this.Db=Q(this.va,ua,this,b);this.vc=Q(this.va,"keydown",this.Ag,b,this);this.Eb=Q(this.va,"keyup",this.Bg,b,this)};
t.detach=function(){this.Db&&(hd(this.Db),hd(this.vc),hd(this.Eb),this.Eb=this.vc=this.Db=null);this.va=null;this.Z=this.D=-1};t.h=function(){Ze.l.h.call(this);this.detach()};var df=function(a,b,c,d){P.call(this,d);this.type="key";this.keyCode=a;this.charCode=b};y(df,P);var ef={},ff=null,gf=function(a){a=a[Va]||(a[Va]=++Wa);delete ef[a];Fb(ef)&&ff&&ff.stop()},jf=function(){ff||(ff=new Se(function(){hf(Za())},20));var a=ff;a.Bb()||a.start()},hf=function(a){Bb(ef,function(b){b.eh(a)});Fb(ef)||jf()};var kf=function(){R.call(this);this.eb=0;this.endTime=this.startTime=null};y(kf,R);t=kf.prototype;t.Hh=function(){this.eb=1};t.Pe=function(){this.eb=0};t.Yd=function(){return 1==this.eb};t.Xd=function(){return-1==this.eb};t.Zd=function(){return 0==this.eb};t.fh=function(){this.U("begin")};t.me=function(){this.U("end")};t.lh=function(){this.U("finish")};t.oh=function(){this.U("play")};t.sh=function(){this.U("resume")};t.th=function(){this.U("stop")};t.U=function(a){this.dispatchEvent(a)};var lf=function(a,b,c,d){kf.call(this);if(!w(a)||!w(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.cb=a;this.ig=b;this.duration=c;this.kd=d;this.coords=[];this.progress=0};y(lf,kf);t=lf.prototype;
t.play=function(a){if(a||this.Zd())this.progress=0,this.coords=this.cb;else if(this.Yd())return!1;gf(this);this.startTime=a=Za();this.Xd()&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.progress||this.fh();this.oh();this.Xd()&&this.sh();this.Hh();var b=this[Va]||(this[Va]=++Wa);b in ef||(ef[b]=this);jf();this.yd(a);return!0};t.stop=function(a){gf(this);this.Pe();a&&(this.progress=1);this.Xe(this.progress);this.th();this.me()};
t.h=function(){this.Zd()||this.stop(!1);this.ih();lf.l.h.call(this)};t.eh=function(a){this.yd(a)};t.yd=function(a){a<this.startTime&&(this.endTime=a+this.endTime-this.startTime,this.startTime=a);this.progress=(a-this.startTime)/(this.endTime-this.startTime);1<this.progress&&(this.progress=1);this.Xe(this.progress);1==this.progress?(this.Pe(),gf(this),this.lh(),this.me()):this.Yd()&&this.$g()};
t.Xe=function(a){Ta(this.kd)&&(a=this.kd(a));this.coords=Array(this.cb.length);for(var b=0;b<this.cb.length;b++)this.coords[b]=(this.ig[b]-this.cb[b])*a+this.cb[b]};t.$g=function(){this.U("animate")};t.ih=function(){this.U("destroy")};t.U=function(a){this.dispatchEvent(new mf(a,this))};var mf=function(a,b){O.call(this,a);this.coords=b.coords;this.y=b.coords[1];this.duration=b.duration;this.progress=b.progress};y(mf,O);var nf=function(a,b,c,d,f,g){function k(q){if(q){q.tabIndex=0;var N=l.Bh;N?q.setAttribute("role",N):q.removeAttribute("role");be(q,"goog-zippy-header");l.gg(q);l.fg(q)}}R.call(this);this.lc=f||Ec();this.ca=this.lc.Na(a)||null;this.La=this.lc.Na(d||null);this.Gb=Ta(b)?b:null;this.Bh=g||"tab";this.V=this.Gb||!b?null:this.lc.Na(b);this.R=1==c;void 0!==c||this.Gb||(this.La?this.R=this.La.style.display!=n:this.ca&&(this.R=ae(this.ca,oa)));this.fe=new Te(this);this.wc=new Ze;this.ke=new Te(this);var l=
this;k(this.ca);k(this.La);this.Nb(this.R)};y(nf,R);t=nf.prototype;t.h=function(){nf.l.h.call(this);Nc(this.fe);Nc(this.wc);Nc(this.ke)};t.collapse=function(){this.Nb(!1)};t.toggle=function(){this.Nb(!this.R)};t.Nb=function(a){this.V?ee(this.V,a):a&&this.Gb&&(this.V=this.Gb());this.V&&be(this.V,"goog-zippy-content");this.La?(ee(this.ca,!a),ee(this.La,a)):this.Sc(a);this.Je(a);this.dispatchEvent(new of("toggle",this,this.R))};t.Je=function(a){this.R=a};
t.Sc=function(a){if(this.ca){var b=this.ca;a?be(b,oa):ce(b,oa);b=this.ca;a?ce(b,ma):be(b,ma);b=this.ca;w(a)&&(a=a.join(" "));""===a||void 0==a?(Re||(Re={atomic:!1,autocomplete:n,dropeffect:n,haspopup:!1,live:"off",multiline:!1,multiselectable:!1,orientation:"vertical",readonly:!1,relevant:"additions text",required:!1,sort:n,busy:!1,disabled:!1,hidden:!1,invalid:"false"}),a=Re,"expanded"in a?b.setAttribute(ea,a.expanded):b.removeAttribute(ea)):b.setAttribute(ea,a)}};
t.fg=function(a){a&&(this.wc.pd(a),this.fe.Da(this.wc,"key",this.nh))};t.gg=function(a){a&&this.ke.Da(a,"click",this.mh)};t.nh=function(a){if(13==a.keyCode||32==a.keyCode)this.toggle(),this.Bd(a),a.preventDefault(),a.stopPropagation()};t.mh=function(a){this.toggle();this.Bd(a)};t.Bd=function(a){this.dispatchEvent(new of("action",this,this.R,a))};var of=function(a,b){O.call(this,a,b)};y(of,O);var pf=function(a,b,c,d,f){d=d||Ec();var g=d.hc("DIV",{style:"overflow:hidden"});b=d.Na(b);b.parentNode.replaceChild(g,b);g.appendChild(b);this.qb=g;this.J=null;nf.call(this,a,b,c,void 0,d,f);a=this.R;this.qb.style.display=a?"":n;this.Sc(a)};y(pf,nf);t=pf.prototype;t.animationDuration=500;t.Tf=function(a){return 1-Math.pow(1-a,3)};
t.Nb=function(a){if(this.R!=a||this.J){this.qb.style.display==n&&(this.qb.style.display="");var b=this.V.offsetHeight;if(this.J){a=this.R;id(this.J);this.J.stop(!1);var c=b-Math.abs(parseInt(this.V.style.marginTop,10))}else c=a?0:b;this.Sc(a);this.J=new lf([0,c],[0,a?b:0],this.animationDuration,this.Tf);Q(this.J,["begin","animate","end"],this.ah,!1,this);Q(this.J,"begin",x(this.bh,this,a));Q(this.J,"end",x(this.dh,this,a));this.J.play(!1)}};
t.ah=function(a){var b=this.V;b.style.marginTop=a.y-b.offsetHeight+"px"};t.bh=function(a){this.dispatchEvent(new of("a",this,a))};t.dh=function(a){a&&(this.V.style.marginTop="0");id(this.J);this.Je(a);this.J=null;a||(this.qb.style.display=n);this.dispatchEvent(new of("toggle",this,a));this.dispatchEvent(new of("b",this,a))};var qf=null;var W=new Pe;v("BLOG_CMT_LoggedInGaiaIdentity",Ie,void 0);v("BLOG_CMT_NotLoggedInGaiaIdentityFactory",Le,void 0);v("BLOG_CMT_NameUrlIdentityFactory",Oe,void 0);v("BLOG_CMT_AnonymousIdentityFactory",Ld,void 0);v("BLOG_CMT_onPost",function(){Qe();return W.ph()},void 0);v("BLOG_CMT_onPreview",function(){return W.qh()},void 0);v("BLOG_CMT_onCommentBodyChange",function(){},void 0);v("BLOG_CMT_onCancel",function(){return W.gh()},void 0);v("BLOG_CMT_onSelectorChange",function(){return W.Ec()},void 0);
v("BLOG_CMT_onContinue",function(){return W.hh()},void 0);v("BLOG_CMT_onEdit",function(){return W.jh()},void 0);v("BLOG_CMT_addIdentity",function(a){return W.cc(a)},void 0);v("BLOG_CMT_addAndSelectIdentity",function(a){return W.ld(a)},void 0);v("BLOG_CMT_addIdentityFactory",function(a){return W.md(a)},void 0);v("BLOG_CMT_addNameUrlIdentityFactory",function(){return W.Qf()},void 0);v("BLOG_CMT_addAnonIdentity",function(){return W.Pf()},void 0);
v("BLOG_CMT_addNotLoggedInGaiaIdentity",function(){return W.Rf()},void 0);v("BLOG_CMT_init",function(a,b){se(document.location.href);W.Ah();W.Ec();W.he();Ge(a,b);K(Fa).value==Ka&&(K(Fa).value="false",xe(K(da),"previewMode"));re();return!0},void 0);v("BLOG_CMT_createPhotoZippy",function(a,b){K(a)&&K(b)&&(qf=new pf(a,b))},void 0);v("BLOG_CMT_closePhotoZippy",function(){null!=qf&&qf.collapse()},void 0);
v("BLOG_CMT_finalizeBG",function(){window.rd&&window.rd.invoke(function(a){document.getElementById(fa).value=a})},void 0);
v("BLOG_CMT_getBG",function(){var a=new Md("/comment-iframe-bg.g"),b=document.getElementById(fa).value;b&&a.Ob(fa,b);b=null;"Microsoft Internet Explorer"==window.navigator.appName&&(document.documentMode?b=document.documentMode:(b=5,document.compatMode&&"CSS1Compat"==document.compatMode&&(b=7)));b&&a.Ob("iemode",b);document.getElementById("pageID")&&a.Ob("page","1");Wd&&a.Ob("bgint",Wd);Cd(a,function(){if(this.Xa()){var c=eval(this.rg());c instanceof Object&&c.length&&(1<c.length&&(eval(c[1]),Wd=
c[2]),window.rd=new botguard.bg(c[0]))}})},void 0);v("BLOG_CMT_setBG",function(a){Wd=a},void 0);v("BLOG_CMT_subscription.toggle",function(){if(!De){De=!0;var a=K("commentSubscriptionForm");Cd(a.action,function(){De=!1;if(this.Xa()){var b=this.Od();null!=b.errorMessage?V(3,b.errorMessage,!0):ue(b.statusMessage);Ge(b.can_subscribe,b.is_subscribed)}else V(3,"An error occurred while contacting the server.",!0)},"POST",Ce(a))}},void 0);v("BLOG_CMT_showStatusMessage",ue,void 0);
v("BLOG_CMT_showPostErrorMessage",function(a){V(4,a,!0)},void 0);v("BLOG_CMT_hidePreview",function(){Qe();W.ab();qe()},void 0);v("BLOG_xhr",S,void 0);S.send=Cd;S.prototype.isSuccess=S.prototype.Xa;S.prototype.getResponseJson=S.prototype.Od;v("$",K,void 0);function rf(a){return function(b){var c=-1;try{c=b.status}catch(d){}return 500<=c?(b.responseText.length?document.body.innerHTML=b.responseText:window.alert(LayoutsMessages.SERVER_ERROR),!1):a?a(b):!0}};var tf=function(a,b,c){var d=a.ownerDocument;b=b._GetHelper();var f=b._GetData(),g=c._GetAllData();a=sf(d,a,h,"widget-wrap1");a=sf(d,a,h,"widget-wrap2");a=sf(d,a,h,"widget-wrap3");var k=sf(d,a,h,"widget-content");if(a=f.version&&1<f.version)k.className+=" visibility",sf(d,k,h,"layout-widget-state "+(f.isVisible?"visible":"not-visible")).setAttribute("title",f.visibilityTooltipMessage);var l=sf(d,k,h,"layout-title");if(f[wa]){var q=sf(d,k,h,va);q.appendChild(d.createTextNode(f[wa]));q.setAttribute("title",
f[va])}l.appendChild(d.createTextNode(f["layout-title"]));f=sf(d,k,"a","editlink");var N=b._GenerateWidgetMetadata();f.setAttribute("href",N.quickEditUrl);f.target=ha;f.onclick=function(){return c._PopupConfig(d.getElementById(N.instanceId))};a&&(f.className+=" icon");f.appendChild(d.createTextNode(g.messages.edit||"Edit"))},sf=function(a,b,c,d){a=a.createElement(c);a.className=d;b.appendChild(a);return a};var uf=function(){this.wh={};this.je={};this.Hc={};this.Ye=null;this.se=[]};Qa(uf);uf.prototype.Jd=function(a,b){return a+"_"+b+".js"};var vf=function(a){eval(a)};uf.prototype.Td=function(a,b){v("__gjsload__",vf,void 0);this.Ye=a.replace(/\.js$/,"");b&&(this.Jd=b);fb(this.se,function(c){this.Tg(c)},this);kb(this.se)};uf.prototype.yh=function(a,b,c){var d=this.je,f=this.wh;d[a]||(d[a]={});if(c)d[a][b]=c;else if(f[a]){for(b=0;b<f[a].length;++b)(0,f[a][b][1])(d[a][f[a][b][0]]);delete f[a];delete this.Hc[a]}};
uf.prototype.Tg=function(a){wd(function(){if(!this.je[a]){var b=this.Jd(this.Ye,a),c=Eb(this.Hc,b);this.Hc[a]=b;if(!c){c=Ic("SCRIPT",{type:"text/javascript"});b=new Qb(Ob,b);b instanceof Qb&&b.constructor===Qb&&b.Kf===Pb?b=b.xe:(Ra(b),b="type_error:TrustedResourceUrl");c.src=b;if(null===Oa)b:{b=u.document;if((b=b.querySelector&&b.querySelector("script[nonce]"))&&(b=b.nonce||b.getAttribute("nonce"))&&Na.test(b)){Oa=b;break b}Oa=""}b=Oa;b&&c.setAttribute("nonce",b);document.body.appendChild(c)}}},0,
this)};var wf=function(){this.K=[];this.O=[]};t=wf.prototype;t.Ug=function(){0==this.K.length&&(this.K=this.O,this.K.reverse(),this.O=[])};t.enqueue=function(a){this.O.push(a)};t.dequeue=function(){this.Ug();return this.K.pop()};t.o=function(){return this.K.length+this.O.length};t.isEmpty=function(){return 0==this.K.length&&0==this.O.length};t.clear=function(){this.K=[];this.O=[]};t.contains=function(a){return z(this.K,a)||z(this.O,a)};
t.remove=function(a){var b=this.K;var c=eb(b,a);0<=c?(Array.prototype.splice.call(b,c,1),b=!0):b=!1;return b||lb(this.O,a)};t.v=function(){for(var a=[],b=this.K.length-1;0<=b;--b)a.push(this.K[b]);var c=this.O.length;for(b=0;b<c;++b)a.push(this.O[b]);return a};var xf=function(a){this.j=new sd;a&&this.addAll(a)},yf=function(a){var b=typeof a;return b==p&&a||b==m?"o"+(a[Va]||(a[Va]=++Wa)):b.substr(0,1)+a};t=xf.prototype;t.o=function(){return this.j.o()};t.add=function(a){this.j.set(yf(a),a)};t.addAll=function(a){a=ud(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])};t.Lb=function(a){a=ud(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};t.remove=function(a){return this.j.remove(yf(a))};t.clear=function(){this.j.clear()};t.isEmpty=function(){return this.j.isEmpty()};
t.contains=function(a){return this.j.ka(yf(a))};t.v=function(){return this.j.v()};t.clone=function(){return new xf(this)};t.ac=function(){return this.j.ac(!1)};var zf=function(a,b){L.call(this);this.ie=a||0;this.Ib=b||10;if(this.ie>this.Ib)throw Error("[goog.structs.Pool] Min can not be greater than max");this.W=new wf;this.ga=new xf;this.delay=0;this.xc=null;this.jb()};y(zf,L);t=zf.prototype;t.tb=function(){var a=Za();if(!(null!=this.xc&&a-this.xc<this.delay)){var b=this.zh();b&&(this.xc=a,this.ga.add(b));return b}};t.Mc=function(a){return this.ga.remove(a)?(this.bc(a),!0):!1};
t.zh=function(){for(var a;0<this.Id()&&(a=this.W.dequeue(),!this.Dc(a));)this.jb();!a&&this.o()<this.Ib&&(a=this.ic());return a};t.bc=function(a){this.ga.remove(a);this.Dc(a)&&this.o()<this.Ib?this.W.enqueue(a):this.kc(a)};t.jb=function(){for(var a=this.W;this.o()<this.ie;)a.enqueue(this.ic());for(;this.o()>this.Ib&&0<this.Id();)this.kc(a.dequeue())};t.ic=function(){return{}};t.kc=function(a){if(typeof a.la==m)a.la();else for(var b in a)a[b]=null};t.Dc=function(a){return typeof a.Wf==m?a.Wf():!0};
t.contains=function(a){return this.W.contains(a)||this.ga.contains(a)};t.o=function(){return this.W.o()+this.ga.o()};t.mg=function(){return this.ga.o()};t.Id=function(){return this.W.o()};t.isEmpty=function(){return this.W.isEmpty()&&this.ga.isEmpty()};t.h=function(){zf.l.h.call(this);if(0<this.mg())throw Error("[goog.structs.Pool] Objects not released");delete this.ga;for(var a=this.W;!a.isEmpty();)this.kc(a.dequeue());delete this.W};var Af=function(a,b){this.ee=a;this.Wc=b};Af.prototype.getKey=function(){return this.ee};Af.prototype.clone=function(){return new Af(this.ee,this.Wc)};var Bf=function(a){this.M=[];a&&this.Ig(a)};t=Bf.prototype;t.Vd=function(a,b){var c=this.M;c.push(new Af(a,b));this.Zg(c.length-1)};t.Ig=function(a){if(a instanceof Bf){var b=a.L();a=a.v();if(0>=this.o()){for(var c=this.M,d=0;d<b.length;d++)c.push(new Af(b[d],a[d]));return}}else b=Db(a),a=Cb(a);for(d=0;d<b.length;d++)this.Vd(b[d],a[d])};t.remove=function(){var a=this.M,b=a.length,c=a[0];if(!(0>=b))return 1==b?kb(a):(a[0]=a.pop(),this.Wg(0)),c.Wc};
t.Wg=function(a){for(var b=this.M,c=b.length,d=b[a];a<c>>1;){var f=this.pg(a),g=this.tg(a);f=g<c&&b[g].getKey()<b[f].getKey()?g:f;if(b[f].getKey()>d.getKey())break;b[a]=b[f];a=f}b[a]=d};t.Zg=function(a){for(var b=this.M,c=b[a];0<a;){var d=this.qg(a);if(b[d].getKey()>c.getKey())b[a]=b[d],a=d;else break}b[a]=c};t.pg=function(a){return 2*a+1};t.tg=function(a){return 2*a+2};t.qg=function(a){return a-1>>1};t.v=function(){for(var a=this.M,b=[],c=a.length,d=0;d<c;d++)b.push(a[d].Wc);return b};
t.L=function(){for(var a=this.M,b=[],c=a.length,d=0;d<c;d++)b.push(a[d].getKey());return b};t.ka=function(a){return ib(this.M,function(b){return b.getKey()==a})};t.clone=function(){return new Bf(this)};t.o=function(){return this.M.length};t.isEmpty=function(){return 0==this.M.length};t.clear=function(){kb(this.M)};var Cf=function(){Bf.call(this)};y(Cf,Bf);Cf.prototype.enqueue=function(a,b){this.Vd(a,b)};Cf.prototype.dequeue=function(){return this.remove()};var Df=function(a,b){this.Ad=void 0;this.Mb=new Cf;zf.call(this,a,b)};y(Df,zf);t=Df.prototype;t.tb=function(a,b){if(!a)return(a=Df.l.tb.call(this))&&this.delay&&(this.Ad=u.setTimeout(x(this.vb,this),this.delay)),a;this.Mb.enqueue(void 0!==b?b:100,a);this.vb()};t.vb=function(){for(var a=this.Mb;0<a.o();){var b=this.tb();if(b)a.dequeue().apply(this,[b]);else break}};t.bc=function(a){Df.l.bc.call(this,a);this.vb()};t.jb=function(){Df.l.jb.call(this);this.vb()};
t.h=function(){Df.l.h.call(this);u.clearTimeout(this.Ad);this.Mb.clear();this.Mb=null};var Ef=function(a,b,c,d){this.pc=a;this.aa=!!d;Df.call(this,b,c)};y(Ef,Df);Ef.prototype.ic=function(){var a=new S,b=this.pc;b&&b.forEach(function(c,d){a.headers.set(d,c)});this.aa&&a.Qc(!0);return a};Ef.prototype.Dc=function(a){return!a.ua&&!a.Bb()};var Ff=function(a,b,c,d,f,g){R.call(this);this.Cc=void 0!==a?a:1;this.sa=void 0!==f?Math.max(0,f):0;this.aa=!!g;this.Ha=new Ef(b,c,d,g);this.N=new sd;this.rb=new Te(this)};y(Ff,R);var Gf=[Ba,e,Ja,"error","abort","timeout"];t=Ff.prototype;t.Pc=function(a){this.sa=Math.max(0,a)};
t.send=function(a,b,c,d,f,g,k,l,q,N){if(this.N.get(a))throw Error("[goog.net.XhrManager] ID in use");b=new Hf(b,x(this.zg,this,a),c,d,f,k,void 0!==l?l:this.Cc,q,void 0!==N?N:this.aa);this.N.set(a,b);a=x(this.wg,this,a);this.Ha.tb(a,g);return b};t.abort=function(a,b){var c=this.N.get(a);if(c){var d=c.Tb;c.Dh(!0);b&&(d&&(this.Ae(d,c.Xc),$c(d,Ba,function(){this.Ha.Mc(d)},!1,this)),this.N.remove(a));d&&d.abort()}};
t.wg=function(a,b){var c=this.N.get(a);c&&!c.Tb?(this.Sf(b,c.Xc),b.Pc(this.sa),b.Gh(c.Fa),b.Qc(c.aa),c.Tb=b,this.dispatchEvent(new If(Ba,this,a,b)),this.De(a,b),c.jd&&b.abort()):this.Ha.Mc(b)};t.zg=function(a,b){var c=b.target;switch(b.type){case Ba:this.De(a,c);break;case e:return this.xg(a,c,b);case Ja:this.Cg(a,c);break;case "timeout":case "error":this.yg(a,c);break;case "abort":this.vg(a,c)}return null};
t.De=function(a,b){var c=this.N.get(a);!c||c.wd||c.oc()?(c&&(this.Ae(b,c.Xc),this.N.remove(a)),this.Ha.Mc(b)):(c.Hg(),b.send(c.getUrl(),c.Vg,c.getContent(),c.pc))};t.xg=function(a,b,c){var d=this.N.get(a);if(7==b.Ca||b.Xa()||d.oc())if(this.dispatchEvent(new If(e,this,a,b)),d&&(d.Eh(!0),d.vd))return d.vd.call(b,c);return null};t.vg=function(a,b){this.dispatchEvent(new If("abort",this,a,b))};t.Cg=function(a,b){this.dispatchEvent(new If(Ja,this,a,b))};
t.yg=function(a,b){this.N.get(a).oc()&&this.dispatchEvent(new If("error",this,a,b))};t.Ae=function(a,b,c){this.rb.Rb(a,c||Gf,b)};t.Sf=function(a,b,c){this.rb.Da(a,c||Gf,b)};t.h=function(){Ff.l.h.call(this);this.Ha.la();this.Ha=null;this.rb.la();this.rb=null;this.N.clear();this.N=null};var If=function(a,b,c,d){O.call(this,a,b);this.id=c;this.Tb=d};y(If,O);
var Hf=function(a,b,c,d,f,g,k,l,q){this.Kh=a;this.Vg=c||"GET";this.Zf=d;this.pc=f||null;this.Cc=void 0!==k?k:1;this.qd=0;this.jd=this.wd=!1;this.Xc=b;this.vd=g;this.Fa=l||"";this.aa=!!q;this.Tb=null};t=Hf.prototype;t.getUrl=function(){return this.Kh};t.getContent=function(){return this.Zf};t.Hg=function(){this.qd++};t.oc=function(){return this.qd>this.Cc};t.Eh=function(a){this.wd=a};t.Dh=function(a){this.jd=a};function Jf(a,b,c,d,f){this.Ua=a;this.Ge=b;this.Fe=c||null;this.data=d||null;if(f){if(this.jc=f,"displayModeSnippet"!=f&&"displayModeFull"!=f&&f!=ja&&f!=ka)throw"bad display mode: "+f;}else this.jc=ka;this.Cb=!1}Jf.prototype.og=function(){return this.Ua};function Kf(a){this.dg=!0;this.A=a;this.Sb=null}t=Kf.prototype;t.If=function(a){this.Sb=a};t.hf=function(){return this.A.data};t.Df=function(a){return this.A.data=a};t.Ff=function(a){return this.A.Cb=a};
t.ef=function(){var a={};a.type=this.Sb.Ve;a.instanceId=this.A.Ua;a.sectionId=this.A.Ge;a.actionUrl=X.fc;a.quickEditUrl=X.Ed+"&widgetType="+this.Sb.Ve+"&widgetId="+this.A.Ua+"&sectionId="+this.A.Ge+"&action="+X.$c;return a};t.$b=function(a,b,c,d){b=b||{};window.__wavt&&(b.xssi_token=window.__wavt);X.$b(a,b,this.A.Ua,this.Sb.Ve,c,d)};function X(){}X.mf=function(a,b,c){X.ia={};X.Ed=a;X.fc=b;X.Th=c;X.Pa={};X.Ub=new Ff;X.le=0;X.Ic=0;Q(X.Ub,Ba,function(){X.Ic++});Q(X.Ub,e,function(){X.Ic--})};
X.Lf=function(a){a=X.bf(a.document);document.body.appendChild(a)};X.Jf=function(a){X.Lf(window);if(window.parent==window){var b="Preview";a&&(b=a);a=X.af(window.document,b);document.body.appendChild(a[0]);document.body.appendChild(a[1])}};X.pf=ha;X.$e=ha;X.$c="editWidget";X.gf=function(){return X.fc};X.Gf=function(a,b){X.Fc=a;X.vh=b};X.kf=function(){return X.Fc};X.Hf=function(a){X.Mh=a};X.ad=function(){return X.Mh};X.Ef=function(a){X.Pa=a};
X.ff=function(){var a={},b;for(b in X.Pa){var c=X.Pa[b];a[c.name]=c.data}c={};for(b in X.ia)c[b]=X.ia[b].w.A.data;a.widgets=c;return a};X.cd=function(a,b){var c=new Kf(b);a=new window[a](c);c.If(a);X.ia[b.Ua]=a;X.Zc(a);return a};X.vf=function(a,b){a=X.cd(a,b);a.w.Ff(!0);return a};X.Zc=function(a){a.w.A.jc!=ka&&(a.w.dg=!1)};X.ta=function(a){return X.ia?X.ia[a]:null};
X.Zb=function(a,b,c,d,f){var g="";d&&(g="&widgetId="+d);a=X.Ed+"&action="+a+"&sectionId="+b+"&widgetType="+c+g;if(window.name==f)return window.location.replace(a),window.focus(),window;f=window.open(a,f,"width=570,height=600,left=75,top=20,resizable=yes,scrollbars=yes");f.focus();return f};
X.tf=function(a){var b=a.getAttribute("id"),c=X.ta(b);if(c){var d=c.w.Ka;if(null!=d&&!d.closed)return d.focus(),!1}d="config"+b;a=X.Zb(X.$c,a.parentNode.getAttribute("id"),a.getAttribute("widgetType"),b,d);c&&(c.w.Ka=a);return!1};X.uf=function(a){X.Zb(X.$e,a.parentNode.getAttribute("id"),a.getAttribute("widgetType"),a.getAttribute("id"),X.pf);return!1};X.cf=function(a,b,c){X.ja(c,c.LayoutsMessages.DELETING);X.ed("delete",{},a,b)};
Kf.prototype.Af=function(a,b){X.ja(b,b.LayoutsMessages.SAVING);this.$b("configure",a)};X.Bf=function(a,b,c){a.sectionid=document.getElementById("sectionId").value;X.ja(c,c.LayoutsMessages.SAVING);X.ed("addnew",a,"",b)};X.Ph=function(a,b,c){b=X.ta(b);b.w.A.Cb?X.Bf(a,c,window):b.w.Af(a,window)};X.$b=function(a,b,c,d,f,g){X.dd(X.fc,a,b,c,d,f,g)};X.ed=function(a,b,c,d,f){X.Fc&&(b.security_token=X.vh,X.dd(X.Fc,a,b,c,d,f))};
X.dd=function(a,b,c,d,f,g,k){b=["action="+encodeURIComponent(b),"widgetId="+encodeURIComponent(d),"widgetType="+encodeURIComponent(f),"responseType=js"];for(var l in c)if(typeof c[l]==p)for(d=c[l],f=0;f<d.length;++f)b.push(encodeURIComponent(l)+"="+encodeURIComponent(d[f]));else b.push(encodeURIComponent(l)+"="+encodeURIComponent(c[l]));var q=g||rf();c=function(){q(this.a)&&window.eval(this.sg())};"GET"==k?(a=0<=a.indexOf("?")?a+"&":a+"?",X.Ub.send(""+X.le++,a+b.join("&"),"GET",void 0,null,null,c)):
X.Ub.send(""+X.le++,a,"POST",b.join("&"),null,null,c)};X.Cf=function(a,b){a&&(a=X.ta(a))&&(a.w.Ka=b)};X.hb=function(a,b){0==X.Ic?a.setTimeout(function(){a.close()},b):a.setTimeout(function(){X.hb(a,b)},200)};X.nf=function(a,b){a&&(X.hb(a,100),X.Mf(a,b))};X.Mf=function(a,b){if(a){var c=a.document.getElementById(Ha);c&&(c=c.innerHTML);c&&a&&a.opener.parent&&a.opener.parent.editor&&a.opener.parent.editor.SetSaveMessage(c,b)}};
X.bd=function(a,b,c){a=X.ia[a];if(null!=c.errors){var d=a?a.w.Ka:null;d||(d=window);X.ja(d,c.errors);a&&a.ib?a.ib(b,c,d):X.ib(c,d)}else a.bd(b,c)};X.ib=function(a,b){a=a["error-details"];for(var c in a)Lf(c,a[c],b.document)};X.qf=function(a,b){window.parent&&window.parent.editor&&b?X.rf(a,b):window.location.replace(window.location.href)};X.rf=function(a,b){var c=X.ta(a);c.w.Df(b.data);a=document.getElementById(a);Mc(a);tf(a,c,X);c.w.Ka=null};
X.lf=function(a,b,c){var d=c[Ga];if(null!=c.errors)X.ja(window,c.errors),X.ib(c,window);else if("addnew"==b){if(X.Xb(window)){if(window.opener&&window.opener.parent)var f=window.opener.parent;f&&f.editor&&f.editor.HandleAddNewWidget(c)}X.ja(window,d);null==window.opener?(a=window.location,b="/rearrange?blogID="+c.blogID,b instanceof C||b instanceof C||(b=typeof b==p&&b.Y?b.T():String(b),Ub.test(b)||(b=ca),b=new C(Rb,b)),a.href=Tb(b)):f&&f._WidgetManager?f._WidgetManager._KillPopupDelay(window):X.hb(window,
100)}else c=X.ia[a],"delete"==b&&(X.ja(c.w.Ka,d),X.df(a,"_OnWidgetDeleted"))};X.sf=function(a){var b=X.ta(a);b&&(b.w.A.jc==ja?top.editor.HandleDeleteWidget(b.w.A.Fe):(b=b.w.A.Fe,b.parentNode.removeChild(b)),delete X.ia[a])};X.df=function(a,b,c){if(X.Xb(window)){var d=window.opener;c||(c=d._WidgetManager[b]);c(a);d._WidgetManager?d._WidgetManager._KillPopupDelay(window,a):X.hb(window,100)}else a=X.ad()+"?widgetId="+a,a+="&func="+encodeURIComponent(b),window.location.replace(a)};
X.Xb=function(a){var b=!1;try{if(a.opener){var c="X"+a.opener.document.domain;c&&"X"!=c&&(b=!0)}}catch(d){}return b};X.fd="status-msg-yellow-on-white";X.ja=function(a,b){a||(a=self);var c=a.document.getElementById(Ha);c&&(c.innerHTML=b);(a=a.document.getElementById(Ga))&&xe(a,X.fd)};X.Nh=function(a){a||(a=self);(a=a.document.getElementById(Ga))&&ze(a,X.fd)};X.Oh=function(a){a&&0<a.length&&"http"!=a.substring(0,4)&&(a="http://"+a);return a};
X.jf=function(a,b){if(z(we(a),b))return a;if(a)for(var c=a.childNodes.length,d=0;d<c;d++){var f=X.jf(a.childNodes.item(d),b);if(f)return f}return null};
X.bf=function(a){a=a.createElement(h);a.className="blogger-clickTrap singleton-element";a.style.position="fixed";a.style.top="0";a.style.left="0";a.style.width="100%";a.style.height="100%";F&&!zc(7)&&(a.style.height="expression(this.parentNode.clientHeight)");a.style.zIndex="1000";a.style.cursor="default";a.onclick=X.Yb;a.onmousedown=X.Yb;a.onmouseup=X.Yb;a.style.background="white";a.style.filter="alpha(opacity=1)";a.style.opacity=".01";a.innerHTML="&nbsp;";return a};
X.af=function(a,b){var c=X.Yc(a,b);a=X.Yc(a,b);c.style.backgroundColor="#000";c.style.border="1px solid #aaa";F&&(c.style.filter=' progid:DXImageTransform.Microsoft.Matrix(sizingMethod="auto expand", M11=0.70710678, M12=0.70710678, M21=-0.70710678, M22=0.70710678) alpha(opacity=50)');c.style.opacity=".5";a.style.border="1px solid transparent";c.style.zIndex=1200;a.style.zIndex=1200;return[c,a]};
X.Yc=function(a,b){a=a.createElement(h);a.style.position="absolute";a.style.top="75px";a.style.left="-225px";a.style.width="600px";a.style.height="28px";a.style.margin="0";a.style.padding="10px";a.style.fontSize="24px";a.style.textAlign="center";a.style.color="#fff";a.style.fontFamily='"trebuchet ms",verdana,arial,sans-serif';F&&(a.style.top="-140px",a.style.left="-140px",a.style.filter=' progid:DXImageTransform.Microsoft.Matrix(sizingMethod="auto expand", M11=0.70710678, M12=0.70710678, M21=-0.70710678, M22=0.70710678)');
a.style.MozTransform=Ca;a.style.MozTransformOrigin="50% 0";a.style.WebkitTransform=Ca;a.style.WebkitTransformOrigin="50% 0";a.innerHTML=b;a.className="singleton-element";return a};X.Rh=function(a){for(var b in X.Pa){var c=X.Pa[b];if(c&&"features"==c.name)return c.data[a]==Ka}return!1};X.Yb=function(a){a||(a=window.event);a&&(a.cancelBubble=!0,a.stopPropagation&&a.stopPropagation());return!1};
var Mf=function(a,b){b||(b=document);return b.getElementById("errormessage_"+a)},Nf=function(a){if(a=Mf(a))Mc(a),a.className="errorbox-good"},Lf=function(a,b,c){if(a=Mf(a,c))a.innerHTML=b,a.className="errorbox-bad errormsg"};v("_WidgetManager",X,void 0);X._Init=X.mf;X._SetPageActionUrl=X.Gf;X._GetPageActionUrl=X.kf;X._SetWidgetRefreshUrl=X.Hf;X._GetWidgetRefreshUrl=X.ad;X._GetCallbackUrl=X.gf;X._DeleteWidgetFromPage=X.cf;X._DisplayWidget=X.Zc;X._GetWidget=X.ta;X._HandleControllerResult=X.bd;
X._HandlePageActionResult=X.lf;X._IsOpenerReachable=X.Xb;X._SetConfigWin=X.Cf;X._SetDataContext=X.Ef;X._SetupPreview=X.Jf;X._RegisterWidget=X.cd;X._RegisterNewWidget=X.vf;X._PopupPaneFromParams=X.Zb;X._PopupConfig=X.tf;X._PopupToolbox=X.uf;X._KillPopupDelay=X.nf;X._OnWidgetConfigured=X.qf;X._OnWidgetDeleted=X.sf;v("_WidgetInfo",Jf,void 0);Jf.prototype._getInstanceId=Jf.prototype.og;Kf.prototype._GetData=Kf.prototype.hf;Kf.prototype._GenerateWidgetMetadata=Kf.prototype.ef;X._GetAllData=X.ff;
v("widget_module_provide",function(a,b,c){uf.ng().yh(a,b,c)},void 0);function Y(a,b,c,d,f,g,k,l){this.C=a;this.sd="null"!=b?b:null;this.ce=c;this.ae=d;this.be=f;this.He=g;this.de=k;this.Ch=l;this.yb=this.Aa=-1;this.rc=null;this.$a=300;this.Bc="200px";this.I=document.getElementById(this.C+"_picImg");this.mb=document.getElementById(this.C+"_changeImageLink");this.xb=document.getElementById(this.C+"_imageChoiceTable");this.sc=document.getElementById(this.C+"_imgSrcFromPCRadio");this.Sd=document.getElementById(this.C+"_imgSrcFromWebRadio");this.f=document.getElementById(this.C+
"_imgFileNameInput");this.Sa=document.getElementById(this.C+"_imgUrlTextInput");this.od=window.frames[this.C+"_asynchronousFileUploadIframe"];this.qc=0;this.s=new Image;this.s.onload=x(this.uh,this);this.s.onerror=x(this.kh,this);this.Gd=!1;this.xa=this.u=this.Fb=null;this.Lc=!1}t=Y.prototype;
t.uh=function(){this.qc=0;Nf(this.C+ba);Nf(this.C+aa);this.sc.checked&&0!=this.Aa||(this.Aa=this.s.width,this.yb=this.s.height,this.rc=this.s.src);var a=1,b=1;this.s.width>this.$a&&(a=this.$a/this.s.width);this.s.height>this.$a&&(b=this.$a/this.s.height);a=Math.min(a,b);this.I.style.width=Math.round(this.s.width*a)+"px";this.I.style.height=Math.round(this.s.height*a)+"px";this.I.src=this.s.src;this.I.style.display="";this.xb.style.display=n;this.mb.style.display="";this.f.disabled=!0;this.ce&&this.ce.call({},
this.I.src,this.rc,this.Aa,this.yb)};t.bb=function(a,b,c,d){a?(Lf(this.C+aa,b),Nf(this.C+ba)):(Lf(this.C+ba,b),Nf(this.C+aa));this.I.style.display=n;this.xb.style.display="";this.mb.style.display=n;this.f.disabled=!1;this.ae&&this.ae.call({},c,d)};t.kh=function(){if(2>this.qc){this.qc++;var a=this.s.src;this.s.src="";this.Ya(a)}else this.bb(this.sc.checked,WidgetMessages.SIV_INVALID_URL,this.I.src,[])};t.Ya=function(a){this.Se();this.s.src=a};
t.Xf=function(a){a=a||window.event;window.event?(a.returnValue=!1,a.cancelBubble=!0):(a.preventDefault(),a.stopPropagation());this.I.style.display=n;this.mb.style.display=n;this.xb.style.display="";this.f.disabled=!1;this.Sa.value="";this.Be();this.Lc=!0;this.be&&this.be.call({})};t.Fg=function(){this.sc.checked=Ka;this.Sa.value="";this.Se();this.Yg();this.Gd=!0;try{this.u.submit()}catch(a){this.bb(!0,WidgetMessages.SIV_INVALID_URL,this.u.value,[])}this.Xg()};
t.gc=function(){var a=this.od.document.result;if(a)if(a.hasErrors)0<a.errors.length?this.bb(!0,a.errors[0].message,this.f.value,a.errors):this.bb(!0,WidgetMessages.SIV_INVALID_URL,this.f.value,a.errors);else{var b=Math.max(a.origWidth,a.origHeight),c=this.Qd();0!=this.Aa&&-1!=c&&b>c?(b=c/b,this.Aa=Math.round(a.origWidth*b),this.yb=Math.round(a.origHeight*b)):(this.Aa=a.origWidth,this.yb=a.origHeight);this.rc=a.mainSrc;this.Ya(a.thumbSrc)}else this.bb(!0,WidgetMessages.SIV_INVALID_URL,this.f.value,
[])};t.Gg=function(a){9!=(a||window.event).keyCode&&(this.Sd.checked=Ka,null!=this.Fb&&(window.clearTimeout(this.Fb),this.Fb=null),a=x(this.Qg,this),this.Fb=window.setTimeout(a,1E3))};t.Qg=function(){if(this.Lc||this.s.src!=this.Sa.value)this.Be(),this.Ya(this.Sa.value);this.Lc=!1};t.Sg=function(a){this.Sd.checked=!0;this.Sa.value=a;this.Ya(a)};
t.Se=function(){this.I.src="https://resources.blogblog.com/img/icon_inprogress.gif";this.I.style.width=this.Bc;this.I.style.height=this.Bc;this.I.style.display="";this.xb.style.display=n;this.mb.style.display=n};
t.Yg=function(){if(!this.u){this.u=document.createElement("form");this.u.action="imageUpload.do";this.u.method="POST";this.u.target=this.od.name;this.u.encoding="multipart/form-data";this.u.style.display=n;if(this.sd){var a=document.createElement(ta);a.type=pa;a.name="blogID";a.value=this.sd;this.u.appendChild(a)}a=document.createElement(ta);a.type=pa;a.name=Da;a.id=Da;this.u.appendChild(a);a=document.createElement(ta);a.type=pa;a.name="security_token";a.value=this.Ch;this.u.appendChild(a);document.body.appendChild(this.u)}a=
this.Qd();-1==a&&(a=1600);document.getElementById(Da).value=a;this.xa={parent:this.f.parentNode,nextSibling:this.f.nextSibling};this.f.parentNode.removeChild(this.f);this.u.appendChild(this.f)};t.Fh=function(a){this.$a=a;this.Bc=a+"px"};t.Xg=function(){this.u.removeChild(this.f);this.xa&&this.xa.nextSibling?this.xa.parent.insertBefore(this.f,this.xa.nextSibling):this.xa.parent.appendChild(this.f)};
t.Be=function(){var a=document.createElement(ta);a.type="file";a.name=this.f.name;a.id=this.f.id;a.onchange=this.f.onchange;var b=this.f.nextSibling;null==b?this.f.parentNode.appendChild(a):this.f.parentNode.insertBefore(a,b);this.f.parentNode.removeChild(this.f);this.f=a};t.Qd=function(){return-1==this.He&&this.de?this.de():this.He};function Z(){this.Vc={}}var Of=new Z;Z.prototype.$f=function(a,b,c,d,f,g,k,l){this.Vc[a]=new Y(a,b,eval(c),eval(d),eval(f),g,eval(k),l);return this.Vc[a]};
Z.prototype.Pd=function(a){return this.Vc[a]};Z.prototype.gc=function(a){(a=this.Pd(a))&&a.Gd&&a.gc()};v("_UploadSimpleImage",Of,void 0);Z.prototype._createUsiContainer=Z.prototype.$f;Z.prototype._getUsiContainer=Z.prototype.Pd;Z.prototype._channelResultArrived=Z.prototype.gc;Y.prototype._changeImage=Y.prototype.Xf;Y.prototype._imgUrlFileOnChange=Y.prototype.Fg;Y.prototype._imgUrlTextOnKeyUp=Y.prototype.Gg;Y.prototype._loadInitialUrl=Y.prototype.Sg;Y.prototype._loadImageFromUrl=Y.prototype.Ya;
Y.prototype._setPreviewSize=Y.prototype.Fh;}).call(this);
