Title
========================================================

From Swinton's __The xtable gallery__

In the markdown's chunk header add the option: results='asis'

Data Frame

```{r, results='asis'}
library(xtable)
data(tli)
## Demonstrate data.frame
tli.table <- xtable(tli[1:10,])
digits(tli.table)[c(2,6)] <- 0
print(tli.table,floating=FALSE, type='html')
```

Matrix

```{r, results='asis'}
design.matrix <- model.matrix(~ sex*grade, data=tli[1:10,])
design.table <- xtable(design.matrix)
print(design.table,floating=FALSE, type='html')
```

lm()

```{r, results='asis'}
fm2 <- lm(tlimth ~ sex*ethnicty, data=tli)
fm2.table <- xtable(fm2)
print(fm2.table,floating=FALSE, type='html')
```

Including Latex code:

```{r, results='asis'}
mat <- round(matrix(c(0.9, 0.89, 200, 0.045, 2.0), c(1, 5)), 4)
rownames(mat) <- "$y_{t-1}$"
colnames(mat) <- c("$R^2$", "$\\bar{R}^2$", "F-stat", "S.E.E", "DW")
mat <- xtable(mat)
print(mat, sanitize.text.function = function(x){x}, type='html')
```

Aligning columns

```{r, results='asis'}
tli.table <- xtable(tli[1:10,])
align(tli.table) <- "cccrlc"
print(tli.table,floating=FALSE, type='html')
```

Suppress row names

```{r, results='asis'}
print((tli.table),include.rownames=FALSE,floating=FALSE, type='html')
```

Suppress column names

```{r, results='asis'}
print((tli.table),include.colnames=FALSE,floating=FALSE, type='html')
```

