---
title: "googleVis egs"
author: "João Neto"
date: "Friday, September 05, 2014"
output: html_document
---

Refs:

+ [http://lamages.blogspot.pt/2014/09/zoom-zoom-googlevis.html](http://lamages.blogspot.pt/2014/09/zoom-zoom-googlevis.html)

+ [http://www.r-bloggers.com/google-charts-in-r-markdown/](http://www.r-bloggers.com/google-charts-in-r-markdown/)

+ [GoogleVis package](http://cran.r-project.org/web/packages/googleVis/index.html)

+ [GoogleVis demos](http://cran.r-project.org/web/packages/googleVis/vignettes/googleVis_examples.html)

+ [Google Chart Gallery](https://developers.google.com/chart/interactive/docs/gallery)

```{r, message=FALSE, warning=FALSE}
library(googleVis)
```


```{r, results='asis'}
set.seed(2020)
x <- seq(0,100,by=0.5)
y <- (50-x)^2+rnorm(length(x),sd=100)
 
curvy <- data.frame(x,y) 
 
gvScat <- gvisScatterChart(curvy,
                   options=list(
                     explorer="{actions: ['dragToZoom', 'rightClickToReset'], maxZoomIn:0.05}",
                     gvis.editor="Edit me!",
                     chartArea="{width:'85%',height:'80%'}",
                     hAxis="{title: 'Click&drag for zoom region, right-click to reset', titleTextStyle: {color: '#000000'}}",
                     vAxis="{title: 'Response y',    titleTextStyle: {color: '#000000'}}",
                     backgroundColor="#EEEEEE",
                     title="Curvilinear Relationship",
                     titleTextStyle="{color:'red', fontName:'Courier', fontSize:12}",  
                     width=550, height=500,
                     legend="none"),
                     chartid="ZoomZoom")
 
print(gvScat,'chart')
```

## More egs


```{r, results='asis'}
df=data.frame(country=c("US", "GB", "BR"), 
               val1=c(10,13,14), 
               val2=c(23,12,32))

gvLine <- gvisLineChart(df)

print(gvLine,'chart')

gvIntensity <- gvisIntensityMap(df)

print(gvIntensity,'chart')
```

```{r}
head(Exports)
```

```{r, results='asis'}
Geo=gvisGeoChart(Exports, locationvar="Country", 
                 colorvar="Profit",
                 options=list(projection="kavrayskiy-vii"))
print(Geo,'chart')
```

Merge charts:

```{r, results='asis'}
G <- gvisGeoChart(Exports, "Country", "Profit", 
                  options=list(width=300, height=300))
T <- gvisTable(Exports, 
               options=list(width=220, height=300))

GT <- gvisMerge(G,T, horizontal=TRUE) 
print(GT,'chart')
```


```{r}
head(Stock)
```

```{r, results='asis'}
gvAnno <- gvisAnnotationChart(Stock, 
                            datevar="Date",
                            numvar="Value", 
                            idvar="Device",
                            titlevar="Title", 
                            annotationvar="Annotation",
                            options=list(
                              width=600, height=350,
                              fill=10, displayExactValues=TRUE,
                              colors="['#0000ff','#00ff00']")
)
plot(gvAnno, 'chart')

AnnoTimeLine  <- gvisAnnotatedTimeLine(Stock, 
                                       datevar="Date",
                                       numvar="Value", 
                                       idvar="Device",
                                       titlevar="Title", 
                                       annotationvar="Annotation",
                                       options=list(displayAnnotations=TRUE,
                                                    width="600px", height="350px"))
plot(AnnoTimeLine, 'chart')

datSK <- data.frame(From=c(rep("A",3), rep("B", 3)),
                    To=c(rep(c("X", "Y", "Z"),2)),
                    Weight=c(5,7,6,2,9,4))

gvSankey <- gvisSankey(datSK, from="From", to="To", weight="Weight",
                     options=list(
                       sankey="{link:  { color: { fill: '#d799ae' } },
                                node:  { color: { fill: '#a61d4c' },
                                label: { color: '#871b47' } }}"))
plot(gvSankey, 'chart')
```

In this org chart, double-click to expand/collapse:


```{r}
head(Regions)
```


```{r, results='asis'}
gvOrg <- gvisOrgChart(Regions, 
                    options=list(width=600, height=250,
                                 size='large', allowCollapse=TRUE))
plot(gvOrg, 'chart')
```


```{r}
head(Population[,-5])
```

```{r, results='asis'}
PopTable <- gvisTable(Population[,-5], 
                      formats=list(Population="#,###",
                                   '% of World Population'='#.#%'),
                      options=list(page='enable'))
plot(PopTable, 'chart')
```


```{r}
head(Andrew)
```

```{r, results='asis'}
GeoMarker <- gvisGeoChart(Andrew, "LatLong", 
                          sizevar='Speed_kt',
                          colorvar="Pressure_mb", 
                          options=list(region="US"))
plot(GeoMarker, 'chart')
```

## Google Maps

```{r, results='asis'}
AndrewMap <- gvisMap(Andrew, "LatLong" , "Tip", 
                     options=list(showTip=TRUE, 
                                  showLine=TRUE, 
                                  enableScrollWheel=TRUE,
                                  mapType='terrain', 
                                  useMapTypeControl=TRUE))
plot(AndrewMap, 'chart')
```

## Flash charts

These charts require Flash.

```{r}
head(Fruits)
```

```{r, results='asis'}
Motion=gvisMotionChart(Fruits, 
                       idvar="Fruit", 
                       timevar="Year")
plot(Motion, 'chart')

myStateSettings <-'
{"xZoomedDataMin":1199145600000,"colorOption":"2",
"duration":{"timeUnit":"Y","multiplier":1},"yLambda":1,
"yAxisOption":"4","sizeOption":"_UNISIZE",
"iconKeySettings":[],"xLambda":1,"nonSelectedAlpha":0,
"xZoomedDataMax":1262304000000,"iconType":"LINE",
"dimensions":{"iconDimensions":["dim0"]},
"showTrails":false,"uniColorForNonSelected":false,
"xAxisOption":"_TIME","orderedByX":false,"playDuration":15000,
"xZoomedIn":false,"time":"2010","yZoomedDataMin":0,
"yZoomedIn":false,"orderedByY":false,"yZoomedDataMax":100}
'
M <- gvisMotionChart(Fruits, "Fruit", "Year", options=list(state=myStateSettings))
plot(M, 'chart')
```

From [http://members.unine.ch/martin.hilpert/motion.html](http://members.unine.ch/martin.hilpert/motion.html):

```{r}
url <- "http://members.unine.ch/martin.hilpert/mot.zip"
fn <- paste0(tempfile(), ".zip")
download.file(url, destfile = fn)
dat <- read.table(unzip(fn, files="mot/convdata.txt", 
                        exdir=tempdir()), 
                  header=TRUE)
library(googleVis)
plot(gvisMotionChart(dat, idvar="VERB", timevar="DECADE",
                     xvar="verbs", yvar="nouns",
                     sizevar="freq", colorvar="skewedness",
                     options=list(width=500, height=450),
                     chartid="Hilpert"))
```

